import type { TelcTest } from './types';

export const tests: TelcTest[] = [
  // ============================================================
  //  TEST 1
  // ============================================================
  {
    id: 1,
    name: "Übungstest 1",
    hoeren: {
      teil1: {
        instruction: "Sie hören sechs kurze Texte. Zu jedem Text gibt es eine Aufgabe. Kreuzen Sie die richtige Antwort an. Sie hören jeden Text zweimal.",
        replays: 2,
        items: [
          {
            id: 1,
            context: "Im Supermarkt",
            audio: "Frau: Entschuldigung, wo finde ich Milch? Mann: Die Milch ist im Kühlregal, gleich dort links. Frau: Danke schön!",
            question: "Die Frau sucht...",
            options: ["a) Brot", "b) Milch", "c) Käse"],
            correct: "b",
          },
          {
            id: 2,
            context: "Am Telefon",
            audio: "Mann: Praxis Doktor Müller, guten Tag. Frau: Guten Tag, ich möchte einen Termin für Mittwoch. Mann: Mittwoch um 10 Uhr ist frei. Frau: Ja, das passt. Danke.",
            question: "Die Frau möchte...",
            options: ["a) ein Medikament kaufen", "b) einen Arzttermin machen", "c) den Doktor sprechen"],
            correct: "b",
          },
          {
            id: 3,
            context: "Am Bahnhof",
            audio: "Achtung, eine Durchsage: Der Zug nach München, Abfahrt 14 Uhr 30, hat 20 Minuten Verspätung. Wir bitten um Entschuldigung.",
            question: "Der Zug nach München...",
            options: ["a) fällt aus", "b) kommt später", "c) fahrt jetzt ab"],
            correct: "b",
          },
          {
            id: 4,
            context: "Im Cafe",
            audio: "Kellner: Was möchten Sie bestellen? Frau: Ich nehme einen Kaffee und ein Stück Kuchen, bitte. Kellner: Gerne. Das macht zusammen 6 Euro 50.",
            question: "Die Frau bestellt...",
            options: ["a) Kaffee und Kuchen", "b) Tee und Kuchen", "c) nur einen Kaffee"],
            correct: "a",
          },
          {
            id: 5,
            context: "Auf der Straße",
            audio: "Mann: Entschuldigung, wie komme ich zum Rathaus? Frau: Gehen Sie geradeaus und dann die zweite Straße rechts. Das Rathaus ist auf der linken Seite.",
            question: "Der Mann sucht...",
            options: ["a) das Krankenhaus", "b) die Schule", "c) das Rathaus"],
            correct: "c",
          },
          {
            id: 6,
            context: "Im Geschäft",
            audio: "Verkaufer: Kann ich Ihnen helfen? Frau: Ja, ich suche einen Pullover in Größe M. Verkaufer: Die Pullover sind dort hinten. Wir haben Rot, Blau und Grun.",
            question: "Die Frau sucht...",
            options: ["a) eine Hose", "b) einen Pullover", "c) ein T-Shirt"],
            correct: "b",
          },
        ],
      },
      teil2: {
        instruction: "Sie hören vier kurze Texte. Zu jedem Text gibt es eine Aufgabe. Kreuzen Sie richtig oder falsch an. Sie hören jeden Text zweimal.",
        replays: 2,
        items: [
          {
            id: 7,
            audio: "Liebe Fahrgäste, der Bus Linie 5 fahrt heute nur bis Marktplatz. Ab Marktplatz nehmen Sie bitte die Linie 8.",
            question: "Der Bus Linie 5 fahrt heute die ganze Strecke.",
            options: ["richtig", "falsch"],
            correct: "falsch",
          },
          {
            id: 8,
            audio: "Auf dem Anrufbeantworter: Hallo Mama, hier ist Lisa. Ich komme am Samstag um 15 Uhr. Kannst du mich vom Bahnhof abholen? Tschuss!",
            question: "Lisa kommt am Samstag.",
            options: ["richtig", "falsch"],
            correct: "richtig",
          },
          {
            id: 9,
            audio: "Achtung! Das Schwimmbad ist am Montag und Dienstag geschlossen. Ab Mittwoch haben wir wieder normal geöffnet.",
            question: "Das Schwimmbad ist am Mittwoch geschlossen.",
            options: ["richtig", "falsch"],
            correct: "falsch",
          },
          {
            id: 10,
            audio: "Heute ist es sonnig und warm. Die Temperaturen liegen bei 28 Grad. Am Abend kommt Regen.",
            question: "Am Abend regnet es.",
            options: ["richtig", "falsch"],
            correct: "richtig",
          },
        ],
      },
      teil3: {
        instruction: "Sie hören fünf kurze Gesprache. Zu jedem Gesprach gibt es eine Aufgabe. Kreuzen Sie die richtige Antwort an. Sie hören jedes Gesprach zweimal.",
        replays: 2,
        items: [
          {
            id: 11,
            audio: "Frau: Was machst du am Wochenende? Mann: Ich gehe am Samstag schwimmen und am Sonntag besuche ich meine Eltern.",
            question: "Was macht der Mann am Samstag?",
            options: ["a) Er besucht seine Eltern.", "b) Er geht schwimmen.", "c) Er arbeitet."],
            correct: "b",
          },
          {
            id: 12,
            audio: "Mann: Wie viel kostet das Buch? Verkäuferin: 12 Euro 90. Mann: Gut, ich nehme es. Kann ich mit Karte bezahlen? Verkäuferin: Ja, natürlich.",
            question: "Wie bezahlt der Mann?",
            options: ["a) bar", "b) mit Karte", "c) mit dem Handy"],
            correct: "b",
          },
          {
            id: 13,
            audio: "Frau: Sprechen Sie Englisch? Mann: Ja, ein bisschen. Und ich spreche auch Französisch. Frau: Oh, toll! Ich lerne gerade Deutsch.",
            question: "Der Mann spricht...",
            options: ["a) nur Deutsch", "b) Englisch und Französisch", "c) nur Englisch"],
            correct: "b",
          },
          {
            id: 14,
            audio: "Mann: Wann beginnt der Deutschkurs? Frau: Der Kurs beginnt am 3. Oktober. Er ist immer montags und mittwochs von 18 bis 20 Uhr.",
            question: "Der Deutschkurs ist...",
            options: ["a) am Wochenende", "b) jeden Tag", "c) montags und mittwochs"],
            correct: "c",
          },
          {
            id: 15,
            audio: "Frau: Ich habe Kopfschmerzen. Mann: Hast du Tabletten genommen? Frau: Nein, noch nicht. Mann: Hier, nimm eine Tablette und trink viel Wasser.",
            question: "Die Frau hat...",
            options: ["a) Bauchschmerzen", "b) Kopfschmerzen", "c) Fieber"],
            correct: "b",
          },
        ],
      },
    },
    lesen: {
      teil1: {
        instruction: "Lesen Sie die Texte. Kreuzen Sie die richtige Antwort an.",
        items: [
          {
            id: 1,
            text: "BIBLIOTHEK\nÖffnungszeiten:\nMo - Fr: 9:00 - 18:00\nSa: 10:00 - 14:00\nSo: geschlossen",
            question: "Wann ist die Bibliothek am Samstag geöffnet?",
            options: ["a) 9:00 - 18:00", "b) 10:00 - 14:00", "c) Sie ist geschlossen."],
            correct: "b",
          },
          {
            id: 2,
            text: "ACHTUNG!\nDer Aufzug ist kaputt.\nBitte benutzen Sie die Treppe.\nWir reparieren den Aufzug am Freitag.",
            question: "Was soll man machen?",
            options: ["a) Den Aufzug benutzen", "b) Die Treppe benutzen", "c) Am Freitag kommen"],
            correct: "b",
          },
          {
            id: 3,
            text: "Deutschkurs A1\nStart: 5. September\nZeit: Dienstag und Donnerstag, 17:00 - 19:00\nPreis: 250 Euro\nAnmeldung: Raum 204",
            question: "Wie viel kostet der Kurs?",
            options: ["a) 204 Euro", "b) 250 Euro", "c) 500 Euro"],
            correct: "b",
          },
          {
            id: 4,
            text: "ZU VERKAUFEN\nFahrrad, rot, 3 Jahre alt\nPreis: 80 Euro\nTelefon: 0171-3456789\nFragen Sie nach Peter.",
            question: "Was wird verkauft?",
            options: ["a) Ein Auto", "b) Ein Fahrrad", "c) Ein Telefon"],
            correct: "b",
          },
          {
            id: 5,
            text: "Liebe Mieter,\nam Donnerstag, 15. März, kein Wasser\nvon 8:00 bis 14:00 Uhr.\nIhre Hausverwaltung",
            question: "Wann gibt es kein Wasser?",
            options: ["a) Am Mittwoch", "b) Am Donnerstag", "c) Am Freitag"],
            correct: "b",
          },
        ],
      },
      teil2: {
        instruction: "Lesen Sie die Texte. Sind die Aussagen richtig oder falsch? Kreuzen Sie an.",
        items: [
          {
            id: 6,
            text: "Restaurant \"Zum goldenen Löffel\"\nWarme Küche: 11:30 - 22:00\nMittagstisch: 11:30 - 14:00 (Tagesgericht 7,50 Euro)\nRuhetag: Montag",
            question: "Am Montag kann man im Restaurant essen.",
            options: ["richtig", "falsch"],
            correct: "falsch",
          },
          {
            id: 7,
            text: "E-Mail: Liebe Maria, ich bin jetzt in Berlin! Die Stadt ist sehr schön. Morgen gehe ich ins Museum. Am Freitag fahre ich zurück nach Köln. Liebe Grüße, Anna",
            question: "Anna ist in Köln.",
            options: ["richtig", "falsch"],
            correct: "falsch",
          },
          {
            id: 8,
            text: "Supermarkt EDEKA\nSonderangebot diese Woche:\nÄpfel 1 kg: 1,99 Euro (statt 2,49 Euro)\nKäse 200g: 2,29 Euro\nMilch 1L: 0,89 Euro",
            question: "Äpfel kosten diese Woche weniger als normal.",
            options: ["richtig", "falsch"],
            correct: "richtig",
          },
          {
            id: 9,
            text: "Hallo zusammen! Unsere Nachbarin Frau Schmidt feiert am 20. April ihren 70. Geburtstag. Wir machen eine Überraschungsparty am 19. April um 15 Uhr im Garten. Bitte bringt Kuchen mit!",
            question: "Die Party ist am 20. April.",
            options: ["richtig", "falsch"],
            correct: "falsch",
          },
          {
            id: 10,
            text: "Arztpraxis Dr. Becker\nSprechstunden:\nMo, Mi, Fr: 8:00 - 12:00 und 14:00 - 18:00\nDi, Do: 8:00 - 12:00\nTermin nur nach Anmeldung!",
            question: "Am Dienstag kann man auch am Nachmittag zum Arzt.",
            options: ["richtig", "falsch"],
            correct: "falsch",
          },
        ],
      },
      teil3: {
        instruction: "Lesen Sie den Text und die Aufgaben. Kreuzen Sie die richtige Antwort an.",
        items: [
          {
            id: 11,
            text: "Mein Name ist Fatima und ich komme aus Marokko. Ich lebe seit zwei Jahren in Hamburg. Ich bin 28 Jahre alt und arbeite als Verkäuferin in einem Modegeschäft. Ich arbeite von Montag bis Freitag, von 9 bis 17 Uhr. Am Wochenende treffe ich meine Freunde. Wir kochen zusammen oder gehen spazieren. Ich spreche Arabisch, Französisch und ein bisschen Deutsch. Ich gehe zweimal pro Woche zum Deutschkurs. Mein Kurs ist abends, von 18 bis 20 Uhr. Ich möchte gut Deutsch lernen, weil ich in Deutschland bleiben möchte.",
            question: "Woher kommt Fatima?",
            options: ["a) Aus der Türkei", "b) Aus Marokko", "c) Aus Frankreich"],
            correct: "b",
          },
          {
            id: 12,
            text: "Mein Name ist Fatima und ich komme aus Marokko. Ich lebe seit zwei Jahren in Hamburg. Ich bin 28 Jahre alt und arbeite als Verkäuferin in einem Modegeschäft. Ich arbeite von Montag bis Freitag, von 9 bis 17 Uhr. Am Wochenende treffe ich meine Freunde. Wir kochen zusammen oder gehen spazieren. Ich spreche Arabisch, Französisch und ein bisschen Deutsch. Ich gehe zweimal pro Woche zum Deutschkurs. Mein Kurs ist abends, von 18 bis 20 Uhr. Ich möchte gut Deutsch lernen, weil ich in Deutschland bleiben möchte.",
            question: "Was macht Fatima am Wochenende?",
            options: ["a) Sie arbeitet.", "b) Sie geht zum Deutschkurs.", "c) Sie trifft Freunde."],
            correct: "c",
          },
          {
            id: 13,
            text: "Mein Name ist Fatima und ich komme aus Marokko. Ich lebe seit zwei Jahren in Hamburg. Ich bin 28 Jahre alt und arbeite als Verkäuferin in einem Modegeschäft. Ich arbeite von Montag bis Freitag, von 9 bis 17 Uhr. Am Wochenende treffe ich meine Freunde. Wir kochen zusammen oder gehen spazieren. Ich spreche Arabisch, Französisch und ein bisschen Deutsch. Ich gehe zweimal pro Woche zum Deutschkurs. Mein Kurs ist abends, von 18 bis 20 Uhr. Ich möchte gut Deutsch lernen, weil ich in Deutschland bleiben möchte.",
            question: "Wie oft geht Fatima zum Deutschkurs?",
            options: ["a) Einmal pro Woche", "b) Zweimal pro Woche", "c) Jeden Tag"],
            correct: "b",
          },
          {
            id: 14,
            text: "Mein Name ist Fatima und ich komme aus Marokko. Ich lebe seit zwei Jahren in Hamburg. Ich bin 28 Jahre alt und arbeite als Verkäuferin in einem Modegeschäft. Ich arbeite von Montag bis Freitag, von 9 bis 17 Uhr. Am Wochenende treffe ich meine Freunde. Wir kochen zusammen oder gehen spazieren. Ich spreche Arabisch, Französisch und ein bisschen Deutsch. Ich gehe zweimal pro Woche zum Deutschkurs. Mein Kurs ist abends, von 18 bis 20 Uhr. Ich möchte gut Deutsch lernen, weil ich in Deutschland bleiben möchte.",
            question: "Wie viele Sprachen spricht Fatima?",
            options: ["a) Zwei", "b) Drei", "c) Vier"],
            correct: "b",
          },
          {
            id: 15,
            text: "Mein Name ist Fatima und ich komme aus Marokko. Ich lebe seit zwei Jahren in Hamburg. Ich bin 28 Jahre alt und arbeite als Verkäuferin in einem Modegeschäft. Ich arbeite von Montag bis Freitag, von 9 bis 17 Uhr. Am Wochenende treffe ich meine Freunde. Wir kochen zusammen oder gehen spazieren. Ich spreche Arabisch, Französisch und ein bisschen Deutsch. Ich gehe zweimal pro Woche zum Deutschkurs. Mein Kurs ist abends, von 18 bis 20 Uhr. Ich möchte gut Deutsch lernen, weil ich in Deutschland bleiben möchte.",
            question: "Warum lernt Fatima Deutsch?",
            options: ["a) Für die Arbeit", "b) Weil sie in Deutschland bleiben möchte", "c) Für eine Reise"],
            correct: "b",
          },
        ],
      },
    },
    schreiben: {
      teil1: {
        instruction: "Sie möchten sich für einen Deutschkurs anmelden. Füllen Sie das Formular aus.",
        formTitle: "Anmeldung Deutschkurs",
        fields: [
          { label: "Vorname", answer: "", hint: "Ihr Vorname" },
          { label: "Nachname", answer: "", hint: "Ihr Nachname" },
          { label: "Geburtsdatum", answer: "", hint: "z.B. 15.03.1995" },
          { label: "Adresse", answer: "", hint: "Straße, Hausnummer, PLZ, Stadt" },
          { label: "Telefonnummer", answer: "", hint: "Ihre Telefonnummer" },
        ],
      },
      teil2: {
        instruction: "Schreiben Sie eine kurze Nachricht (circa 30 Wörter).",
        situation: "Ihr Freund Peter hat Geburtstag. Sie können nicht zur Party kommen. Schreiben Sie Peter eine Nachricht.",
        bullets: [
          "Sagen Sie: Herzlichen Glückwunsch!",
          "Sie können nicht kommen. Warum?",
          "Schlagen Sie einen anderen Termin vor.",
        ],
        minWords: 30,
      },
    },
    sprechen: {
      teil1: {
        teil: 1,
        instruction: "Sich vorstellen: Sagen Sie etwas über sich. Die Stichworte helfen Ihnen.",
        prompts: ["Name?", "Alter?", "Land?", "Wohnort?", "Sprachen?", "Beruf / Arbeit?", "Hobbys?"],
        exampleResponse: "Ich heiße Maria. Ich bin 30 Jahre alt. Ich komme aus Spanien. Ich wohne in Berlin. Ich spreche Spanisch und ein bisschen Deutsch. Ich arbeite als Lehrerin. Meine Hobbys sind Lesen und Kochen.",
      },
      teil2: {
        teil: 2,
        instruction: "Über ein Thema sprechen: Sie bekommen eine Karte mit einem Thema. Stellen Sie Fragen und antworten Sie.",
        prompts: ["Essen und Trinken: Was essen Sie gern? Was trinken Sie zum Frühstück?", "Familie: Haben Sie Geschwister? Wo leben Ihre Eltern?", "Wohnung: Wo wohnen Sie? Wie ist Ihre Wohnung?", "Freizeit: Was machen Sie in der Freizeit? Treiben Sie Sport?"],
      },
      teil3: {
        teil: 3,
        instruction: "Bitten formulieren und darauf reagieren: Bitten Sie um etwas und reagieren Sie auf Bitten.",
        prompts: ["Sie sind im Deutschkurs. Bitten Sie Ihren Nachbarn um einen Kugelschreiber.", "Sie sind im Supermarkt. Fragen Sie, wo die Milch ist.", "Sie sind beim Arzt. Bitten Sie um einen Termin für nächste Woche."],
      },
    },
  },

  // ============================================================
  //  TEST 2
  // ============================================================
  {
    id: 2,
    name: "Übungstest 2",
    hoeren: {
      teil1: {
        instruction: "Sie hören sechs kurze Texte. Zu jedem Text gibt es eine Aufgabe. Kreuzen Sie die richtige Antwort an. Sie hören jeden Text zweimal.",
        replays: 2,
        items: [
          {
            id: 1,
            context: "Im Hotel",
            audio: "Rezeptionist: Guten Abend. Wie kann ich Ihnen helfen? Gast: Ich habe ein Zimmer reserviert. Mein Name ist Weber. Rezeptionist: Ah ja, Herr Weber. Zimmer 305, dritter Stock. Hier ist Ihr Schlüssel.",
            question: "Herr Weber ist...",
            options: ["a) im Restaurant", "b) im Hotel", "c) am Bahnhof"],
            correct: "b",
          },
          {
            id: 2,
            context: "Beim Arzt",
            audio: "Arzt: Was fehlt Ihnen? Patient: Ich habe seit drei Tagen Halsschmerzen und Fieber. Arzt: Ich verschreibe Ihnen Tabletten. Nehmen Sie dreimal taglich eine Tablette.",
            question: "Der Patient hat...",
            options: ["a) Kopfschmerzen", "b) Halsschmerzen und Fieber", "c) Bauchschmerzen"],
            correct: "b",
          },
          {
            id: 3,
            context: "Im Bus",
            audio: "Nachste Haltestelle: Marktplatz. Umsteigen zur Linie 3 Richtung Hauptbahnhof. Bitte vergessen Sie Ihre Sachen nicht.",
            question: "An der nächsten Haltestelle kann man...",
            options: ["a) einkaufen", "b) umsteigen", "c) aussteigen und bleiben"],
            correct: "b",
          },
          {
            id: 4,
            context: "Am Telefon",
            audio: "Frau: Hallo Thomas, hier ist Sabine. Kommst du heute Abend zum Essen? Ich koche Spaghetti. Mann: Oh ja, gerne! Um wie viel Uhr? Frau: Um 19 Uhr. Mann: Super, bis dann!",
            question: "Thomas kommt zum...",
            options: ["a) Frühstück", "b) Mittagessen", "c) Abendessen"],
            correct: "c",
          },
          {
            id: 5,
            context: "Im Park",
            audio: "Frau: Schönes Wetter heute, oder? Mann: Ja, endlich Sonne! Sollen wir ein Eis essen? Frau: Gute Idee! Dort drüben ist eine Eisdiele.",
            question: "Was möchten die beiden machen?",
            options: ["a) Spazieren gehen", "b) Ein Eis essen", "c) Nach Hause gehen"],
            correct: "b",
          },
          {
            id: 6,
            context: "In der Schule",
            audio: "Lehrerin: Morgen schreiben wir einen Test. Bitte lernt die Wörter auf Seite 45. Der Test ist um 9 Uhr. Schüler: Mussen wir auch die Grammatik lernen? Lehrerin: Ja, auch die Grammatik.",
            question: "Morgen gibt es...",
            options: ["a) keinen Unterricht", "b) einen Test", "c) eine Party"],
            correct: "b",
          },
        ],
      },
      teil2: {
        instruction: "Sie hören vier kurze Texte. Kreuzen Sie richtig oder falsch an. Sie hören jeden Text zweimal.",
        replays: 2,
        items: [
          {
            id: 7,
            audio: "Die Apotheke am Marktplatz hat neue Öffnungszeiten: Montag bis Freitag von 8 bis 19 Uhr. Samstags haben wir jetzt auch geöffnet, von 9 bis 13 Uhr.",
            question: "Die Apotheke ist am Samstag geschlossen.",
            options: ["richtig", "falsch"],
            correct: "falsch",
          },
          {
            id: 8,
            audio: "Auf dem Anrufbeantworter: Hallo Schatz, ich komme heute später nach Hause. Ich muss bis 20 Uhr arbeiten. Bitte iss schon ohne mich. Kuss!",
            question: "Die Person kommt später nach Hause.",
            options: ["richtig", "falsch"],
            correct: "richtig",
          },
          {
            id: 9,
            audio: "Liebe Eltern, der Elternabend findet am Donnerstag, den 12. November, um 19 Uhr in der Aula statt. Bitte kommen Sie pünktlich.",
            question: "Der Elternabend ist am Freitag.",
            options: ["richtig", "falsch"],
            correct: "falsch",
          },
          {
            id: 10,
            audio: "Für morgen meldet der Wetterdienst starken Regen und Gewitter. Die Temperaturen fallen auf 12 Grad. Nehmen Sie einen Regenschirm mit.",
            question: "Morgen scheint die Sonne.",
            options: ["richtig", "falsch"],
            correct: "falsch",
          },
        ],
      },
      teil3: {
        instruction: "Sie hören fünf kurze Gesprache. Kreuzen Sie die richtige Antwort an. Sie hören jedes Gesprach zweimal.",
        replays: 2,
        items: [
          {
            id: 11,
            audio: "Frau: Wohin fahrst du im Urlaub? Mann: Wir fahren nach Italien, ans Meer. Frau: Wie schön! Wie lange? Mann: Zwei Wochen.",
            question: "Wohin fahrt der Mann im Urlaub?",
            options: ["a) Nach Spanien", "b) Nach Italien", "c) Nach Frankreich"],
            correct: "b",
          },
          {
            id: 12,
            audio: "Mann: Ich möchte ein Kilo Tomaten, bitte. Verkäuferin: Gerne. Noch etwas? Mann: Ja, zwei Paprika und eine Gurke. Verkäuferin: Das macht 4 Euro 80.",
            question: "Wo ist der Mann?",
            options: ["a) In der Backerei", "b) Im Gemüseladen", "c) In der Metzgerei"],
            correct: "b",
          },
          {
            id: 13,
            audio: "Frau: Entschuldigung, ist der Platz frei? Mann: Ja, bitte. Setzen Sie sich. Frau: Danke. Fahren Sie auch nach Köln? Mann: Nein, ich steige in Bonn aus.",
            question: "Wo steigt der Mann aus?",
            options: ["a) In Köln", "b) In Bonn", "c) In Frankfurt"],
            correct: "b",
          },
          {
            id: 14,
            audio: "Mann: Hast du heute Nachmittag Zeit? Frau: Nein, leider nicht. Ich habe einen Arzttermin um 15 Uhr. Mann: Und morgen? Frau: Morgen passt es!",
            question: "Wann hat die Frau einen Arzttermin?",
            options: ["a) Heute Vormittag", "b) Heute Nachmittag", "c) Morgen"],
            correct: "b",
          },
          {
            id: 15,
            audio: "Mutter: Was wünschst du dir zum Geburtstag? Kind: Ich möchte ein neues Handy! Mutter: Ein Handy? Das ist aber teuer. Kind: Oder ein Computerspiel.",
            question: "Das Kind wünscht sich...",
            options: ["a) Kleidung", "b) ein Handy oder Computerspiel", "c) Geld"],
            correct: "b",
          },
        ],
      },
    },
    lesen: {
      teil1: {
        instruction: "Lesen Sie die Texte. Kreuzen Sie die richtige Antwort an.",
        items: [
          {
            id: 1,
            text: "KINO STAR\nFilm: \"Mein Sommer\"\nDi - So: 17:00 und 20:00\nEintritt: 9 Euro (ermäßigt: 6,50 Euro)\nMontag: Ruhetag",
            question: "Wie viel kostet eine normale Kinokarte?",
            options: ["a) 6,50 Euro", "b) 9 Euro", "c) 17 Euro"],
            correct: "b",
          },
          {
            id: 2,
            text: "Achtung, Baustelle!\nDie Hauptstraße ist vom 1. bis 15. Juni gesperrt.\nUmleitung über Bergstraße.\nWir bitten um Ihr Verständnis.",
            question: "Die Hauptstraße ist...",
            options: ["a) immer offen", "b) zwei Wochen gesperrt", "c) für immer geschlossen"],
            correct: "b",
          },
          {
            id: 3,
            text: "WOCHENMARKT\nJeden Mittwoch und Samstag\nvon 7:00 bis 13:00 Uhr\nauf dem Rathausplatz\nFrisches Obst, Gemüse, Brot, Käse",
            question: "Wann ist der Wochenmarkt?",
            options: ["a) Jeden Tag", "b) Mittwoch und Samstag", "c) Nur am Samstag"],
            correct: "b",
          },
          {
            id: 4,
            text: "Zimmer frei!\n2-Zimmer-Wohnung, 55 qm\nKüche, Bad, Balkon\nKaltmiete: 480 Euro + Nebenkosten\nAb 1. August frei. Tel: 030-12345",
            question: "Wie groß ist die Wohnung?",
            options: ["a) 2 Zimmer", "b) 55 Quadratmeter", "c) 480 Quadratmeter"],
            correct: "b",
          },
          {
            id: 5,
            text: "Fitnessstudio FIT & FUN\nProbetraining gratis!\nÖffnungszeiten: Mo-Fr 6:00-22:00, Sa-So 8:00-20:00\nMonatsbeitrag ab 29,90 Euro",
            question: "Das Probetraining...",
            options: ["a) kostet 29,90 Euro", "b) ist kostenlos", "c) ist nur am Wochenende"],
            correct: "b",
          },
        ],
      },
      teil2: {
        instruction: "Lesen Sie die Texte. Sind die Aussagen richtig oder falsch?",
        items: [
          {
            id: 6,
            text: "E-Mail: Lieber Herr Müller, leider muss ich unseren Termin am Dienstag absagen. Ich bin krank. Können wir den Termin auf nächste Woche verschieben? Mit freundlichen Grüßen, K. Schmidt",
            question: "Herr Schmidt kommt am Dienstag.",
            options: ["richtig", "falsch"],
            correct: "falsch",
          },
          {
            id: 7,
            text: "Jugendherberge Berlin\nEinzelzimmer: 35 Euro / Nacht\nDoppelzimmer: 55 Euro / Nacht\nFrühstück inklusive!\nCheck-in ab 14 Uhr, Check-out bis 11 Uhr",
            question: "Das Frühstück kostet extra.",
            options: ["richtig", "falsch"],
            correct: "falsch",
          },
          {
            id: 8,
            text: "Hallo! Mein Name ist Carlos. Ich bin 45 Jahre alt und komme aus Brasilien. Seit 6 Monaten wohne ich in Frankfurt. Ich arbeite als Koch in einem italienischen Restaurant. Ich finde Deutschland sehr interessant.",
            question: "Carlos wohnt seit einem Jahr in Frankfurt.",
            options: ["richtig", "falsch"],
            correct: "falsch",
          },
          {
            id: 9,
            text: "VOLKSHOCHSCHULE\nNeue Kurse ab September:\n- Deutsch A1 (Mo+Mi, 18-20 Uhr)\n- Yoga (Di, 17-18 Uhr)\n- Kochen (Sa, 10-13 Uhr)\nAnmeldung online oder im Buro.",
            question: "Man kann sich auch im Internet anmelden.",
            options: ["richtig", "falsch"],
            correct: "richtig",
          },
          {
            id: 10,
            text: "SMS: Hi Mama, bin gut in München angekommen. Das Hotel ist super! Morgen früh gehe ich ins Deutsche Museum. Abends treffe ich Tante Helga zum Essen. Kuss!",
            question: "Die Person geht morgen Abend ins Museum.",
            options: ["richtig", "falsch"],
            correct: "falsch",
          },
        ],
      },
      teil3: {
        instruction: "Lesen Sie den Text und die Aufgaben. Kreuzen Sie die richtige Antwort an.",
        items: [
          {
            id: 11,
            text: "Ich bin Kenji und komme aus Japan. Seit einem Jahr wohne ich in München und studiere Informatik an der Universitat. Ich wohne in einem Studentenwohnheim. Mein Zimmer ist klein, aber gemütlich. In meiner Freizeit spiele ich gern Gitarre und gehe joggen. Am Wochenende koche ich japanisches Essen für meine Freunde. Sie finden Sushi und Ramen sehr lecker. Ich finde das Leben in Deutschland gut, aber manchmal vermisse ich meine Familie. Wir telefonieren jeden Sonntag.",
            question: "Was studiert Kenji?",
            options: ["a) Medizin", "b) Informatik", "c) Musik"],
            correct: "b",
          },
          {
            id: 12,
            text: "Ich bin Kenji und komme aus Japan. Seit einem Jahr wohne ich in München und studiere Informatik an der Universitat. Ich wohne in einem Studentenwohnheim. Mein Zimmer ist klein, aber gemütlich. In meiner Freizeit spiele ich gern Gitarre und gehe joggen. Am Wochenende koche ich japanisches Essen für meine Freunde. Sie finden Sushi und Ramen sehr lecker. Ich finde das Leben in Deutschland gut, aber manchmal vermisse ich meine Familie. Wir telefonieren jeden Sonntag.",
            question: "Wo wohnt Kenji?",
            options: ["a) In einer Wohnung", "b) Im Studentenwohnheim", "c) Bei einer Familie"],
            correct: "b",
          },
          {
            id: 13,
            text: "Ich bin Kenji und komme aus Japan. Seit einem Jahr wohne ich in München und studiere Informatik an der Universitat. Ich wohne in einem Studentenwohnheim. Mein Zimmer ist klein, aber gemütlich. In meiner Freizeit spiele ich gern Gitarre und gehe joggen. Am Wochenende koche ich japanisches Essen für meine Freunde. Sie finden Sushi und Ramen sehr lecker. Ich finde das Leben in Deutschland gut, aber manchmal vermisse ich meine Familie. Wir telefonieren jeden Sonntag.",
            question: "Was kocht Kenji am Wochenende?",
            options: ["a) Deutsches Essen", "b) Japanisches Essen", "c) Italienisches Essen"],
            correct: "b",
          },
          {
            id: 14,
            text: "Ich bin Kenji und komme aus Japan. Seit einem Jahr wohne ich in München und studiere Informatik an der Universitat. Ich wohne in einem Studentenwohnheim. Mein Zimmer ist klein, aber gemütlich. In meiner Freizeit spiele ich gern Gitarre und gehe joggen. Am Wochenende koche ich japanisches Essen für meine Freunde. Sie finden Sushi und Ramen sehr lecker. Ich finde das Leben in Deutschland gut, aber manchmal vermisse ich meine Familie. Wir telefonieren jeden Sonntag.",
            question: "Kenji telefoniert mit seiner Familie...",
            options: ["a) jeden Tag", "b) jeden Sonntag", "c) jeden Monat"],
            correct: "b",
          },
          {
            id: 15,
            text: "Ich bin Kenji und komme aus Japan. Seit einem Jahr wohne ich in München und studiere Informatik an der Universitat. Ich wohne in einem Studentenwohnheim. Mein Zimmer ist klein, aber gemütlich. In meiner Freizeit spiele ich gern Gitarre und gehe joggen. Am Wochenende koche ich japanisches Essen für meine Freunde. Sie finden Sushi und Ramen sehr lecker. Ich finde das Leben in Deutschland gut, aber manchmal vermisse ich meine Familie. Wir telefonieren jeden Sonntag.",
            question: "Wie findet Kenji das Leben in Deutschland?",
            options: ["a) Schlecht", "b) Gut", "c) Langweilig"],
            correct: "b",
          },
        ],
      },
    },
    schreiben: {
      teil1: {
        instruction: "Sie möchten ein Hotelzimmer reservieren. Füllen Sie das Formular aus.",
        formTitle: "Hotel Reservation",
        fields: [
          { label: "Name", answer: "", hint: "Ihr voller Name" },
          { label: "Anreise (Datum)", answer: "", hint: "z.B. 10.07.2025" },
          { label: "Abreise (Datum)", answer: "", hint: "z.B. 15.07.2025" },
          { label: "Zimmertyp", answer: "", hint: "Einzelzimmer / Doppelzimmer" },
          { label: "E-Mail", answer: "", hint: "Ihre E-Mail-Adresse" },
        ],
      },
      teil2: {
        instruction: "Schreiben Sie eine kurze Nachricht (circa 30 Wörter).",
        situation: "Sie können morgen nicht zum Deutschkurs kommen. Schreiben Sie eine Nachricht an Ihren Lehrer / Ihre Lehrerin.",
        bullets: [
          "Warum können Sie nicht kommen?",
          "Wann kommen Sie wieder?",
          "Bitten Sie um die Hausaufgaben.",
        ],
        minWords: 30,
      },
    },
    sprechen: {
      teil1: {
        teil: 1,
        instruction: "Sich vorstellen: Sagen Sie etwas über sich.",
        prompts: ["Name?", "Alter?", "Land?", "Wohnort?", "Sprachen?", "Beruf / Arbeit?", "Hobbys?"],
      },
      teil2: {
        teil: 2,
        instruction: "Über ein Thema sprechen: Stellen Sie Fragen und antworten Sie.",
        prompts: ["Einkaufen: Wo kaufen Sie ein? Was kaufen Sie gern?", "Tagesablauf: Wann stehen Sie auf? Was machen Sie am Morgen?", "Reisen: Wohin reisen Sie gern? Mit wem reisen Sie?", "Gesundheit: Was machen Sie für Ihre Gesundheit? Treiben Sie Sport?"],
      },
      teil3: {
        teil: 3,
        instruction: "Bitten formulieren und darauf reagieren.",
        prompts: ["Sie sind in der Bibliothek. Fragen Sie nach einem Buch über Deutschland.", "Sie sind im Zug. Bitten Sie Ihren Nachbarn, das Fenster zu öffnen.", "Sie möchten Ihren Termin beim Arzt andern. Rufen Sie an."],
      },
    },
  },

  // ============================================================
  //  TEST 3
  // ============================================================
  {
    id: 3,
    name: "Übungstest 3",
    hoeren: {
      teil1: {
        instruction: "Sie hören sechs kurze Texte. Zu jedem Text gibt es eine Aufgabe. Kreuzen Sie die richtige Antwort an. Sie hören jeden Text zweimal.",
        replays: 2,
        items: [
          {
            id: 1,
            context: "Auf der Post",
            audio: "Mann: Ich möchte dieses Paket nach Frankreich schicken. Postangestellte: Wie schwer ist es? Mann: Etwa 2 Kilo. Postangestellte: Das kostet 15 Euro 90. Soll ich auch eine Sendungsverfolgung machen?",
            question: "Der Mann möchte...",
            options: ["a) einen Brief schicken", "b) ein Paket schicken", "c) Briefmarken kaufen"],
            correct: "b",
          },
          {
            id: 2,
            context: "In der Küche",
            audio: "Frau: Was kochst du? Mann: Ich mache eine Gemüsesuppe. Mit Kartoffeln, Karotten und Zwiebeln. Frau: Mmm, das riecht gut! Ist sie bald fertig? Mann: In 10 Minuten.",
            question: "Der Mann kocht...",
            options: ["a) Fleisch", "b) Suppe", "c) Kuchen"],
            correct: "b",
          },
          {
            id: 3,
            context: "Im Buro",
            audio: "Chef: Frau Klein, können Sie bitte den Brief an Firma Müller schreiben? Frau Klein: Ja, natürlich. Bis wann brauchen Sie ihn? Chef: Bis heute Nachmittag, bitte.",
            question: "Frau Klein soll...",
            options: ["a) einen Brief schreiben", "b) anrufen", "c) eine E-Mail lesen"],
            correct: "a",
          },
          {
            id: 4,
            context: "Im Kaufhaus",
            audio: "Verkäuferin: Kann ich Ihnen helfen? Kundin: Ja, ich suche ein Geschenk für meine Mutter. Verkäuferin: Wie ware es mit einem Schal? Wir haben sehr schöne aus Seide. Kundin: Oh ja, der blaue gefällt mir!",
            question: "Die Kundin sucht...",
            options: ["a) etwas für sich", "b) ein Geschenk", "c) einen Mantel"],
            correct: "b",
          },
          {
            id: 5,
            context: "Am Telefon",
            audio: "Frau: Zahnarztpraxis Dr. Lang, guten Tag. Mann: Guten Tag, ich habe starke Zahnschmerzen. Kann ich heute noch kommen? Frau: Moment... Ja, um 16:30 Uhr ware ein Termin frei.",
            question: "Der Mann hat...",
            options: ["a) Kopfschmerzen", "b) Zahnschmerzen", "c) Rückenschmerzen"],
            correct: "b",
          },
          {
            id: 6,
            context: "Im Sportverein",
            audio: "Trainer: Unser Fußballtraining ist immer dienstags und donnerstags um 18 Uhr. Am Samstag haben wir oft Spiele. Wer mitmachen möchte, bringt bitte Sportschuhe mit.",
            question: "Das Training ist...",
            options: ["a) am Montag und Mittwoch", "b) am Dienstag und Donnerstag", "c) nur am Samstag"],
            correct: "b",
          },
        ],
      },
      teil2: {
        instruction: "Sie hören vier kurze Texte. Kreuzen Sie richtig oder falsch an. Sie hören jeden Text zweimal.",
        replays: 2,
        items: [
          {
            id: 7,
            audio: "Die Stadtbibliothek bietet ab nächster Woche einen kostenlosen Computerkurs für Anfänger an. Der Kurs ist jeden Mittwoch von 10 bis 12 Uhr. Bitte melden Sie sich an der Information an.",
            question: "Der Computerkurs kostet Geld.",
            options: ["richtig", "falsch"],
            correct: "falsch",
          },
          {
            id: 8,
            audio: "SMS: Lieber Tom, vergiss nicht: Morgen um 8 Uhr Zahnarzt! Danach können wir zusammen fruhstucken. Mama",
            question: "Tom geht morgen zum Zahnarzt.",
            options: ["richtig", "falsch"],
            correct: "richtig",
          },
          {
            id: 9,
            audio: "Achtung: Der Spielplatz am Stadtpark wird renoviert. Er ist bis Ende August geschlossen. Der nächste Spielplatz ist in der Gartenstraße.",
            question: "Der Spielplatz ist im September wieder offen.",
            options: ["richtig", "falsch"],
            correct: "richtig",
          },
          {
            id: 10,
            audio: "Guten Morgen, liebe Zuhörer! Hier ist das Morgenradio. Heute wird es bewölkt, aber trocken. Die Temperaturen liegen bei 15 Grad. Erst am Wochenende kommt die Sonne zurück.",
            question: "Heute scheint die Sonne.",
            options: ["richtig", "falsch"],
            correct: "falsch",
          },
        ],
      },
      teil3: {
        instruction: "Sie hören fünf kurze Gesprache. Kreuzen Sie die richtige Antwort an. Sie hören jedes Gesprach zweimal.",
        replays: 2,
        items: [
          {
            id: 11,
            audio: "Frau: Seit wann lernst du Deutsch? Mann: Seit 8 Monaten. Ich gehe dreimal pro Woche zum Kurs. Frau: Und? Gefällt es dir? Mann: Ja, aber die Grammatik ist schwer!",
            question: "Wie lange lernt der Mann Deutsch?",
            options: ["a) Seit 3 Monaten", "b) Seit 8 Monaten", "c) Seit einem Jahr"],
            correct: "b",
          },
          {
            id: 12,
            audio: "Frau: Mein Sohn ist 6 und kommt nächstes Jahr in die Schule. Mann: Oh, das ist aufregend! Meine Tochter ist schon in der dritten Klasse. Frau: Gefällt ihr die Schule? Mann: Ja, besonders Mathe mag sie.",
            question: "Wie alt ist der Sohn der Frau?",
            options: ["a) 3 Jahre", "b) 6 Jahre", "c) 8 Jahre"],
            correct: "b",
          },
          {
            id: 13,
            audio: "Mann: Ich fahre morgen mit dem Auto nach Hamburg. Frau: Wie lange dauert das? Mann: Etwa 4 Stunden. Frau: Warum nimmst du nicht den Zug? Mann: Der Zug ist zu teuer.",
            question: "Wie fahrt der Mann nach Hamburg?",
            options: ["a) Mit dem Zug", "b) Mit dem Auto", "c) Mit dem Bus"],
            correct: "b",
          },
          {
            id: 14,
            audio: "Frau: Was kostet der Tisch? Verkaufer: 299 Euro. Frau: Und die Stühle? Verkaufer: Ein Stuhl kostet 79 Euro. Im Set mit vier Stühlen 280 Euro. Frau: Gut, ich nehme den Tisch und vier Stühle.",
            question: "Die Frau kauft...",
            options: ["a) nur den Tisch", "b) den Tisch und vier Stühle", "c) nur Stühle"],
            correct: "b",
          },
          {
            id: 15,
            audio: "Mann: Wo warst du gestern? Frau: Ich war im Kino. Der Film war toll! Mann: Was für ein Film? Frau: Eine Komodie, auf Deutsch. Ich habe viel gelacht.",
            question: "Was hat die Frau gestern gemacht?",
            options: ["a) Sie war im Theater.", "b) Sie war im Kino.", "c) Sie war zu Hause."],
            correct: "b",
          },
        ],
      },
    },
    lesen: {
      teil1: {
        instruction: "Lesen Sie die Texte. Kreuzen Sie die richtige Antwort an.",
        items: [
          {
            id: 1,
            text: "SPRACHSCHULE DIALOG\nIntensivkurs Deutsch A1\nDauer: 4 Wochen (Mo-Fr, 9:00-13:00)\nPreis: 399 Euro (Bücher inklusive)\nNachster Start: 2. Januar",
            question: "Wie lange dauert der Kurs?",
            options: ["a) 2 Wochen", "b) 4 Wochen", "c) 6 Wochen"],
            correct: "b",
          },
          {
            id: 2,
            text: "BITTE NICHT PARKEN!\nMontag, 8. Mai\nUmzug von 7:00 bis 16:00 Uhr\nBrauchen Platz für den LKW\nDanke für Ihr Verständnis!",
            question: "Warum soll man nicht parken?",
            options: ["a) Es gibt Bauarbeiten.", "b) Es gibt einen Umzug.", "c) Die Straße ist gesperrt."],
            correct: "b",
          },
          {
            id: 3,
            text: "Flohmarkt!\nWann: Samstag, 15. Juli, 8:00 - 15:00\nWo: Schulhof der Goethe-Schule\nVerkaufen Sie Ihre alten Sachen!\nStandgebühr: 5 Euro\nAnmeldung bei Frau Weber: 0171-9876543",
            question: "Was kann man auf dem Flohmarkt machen?",
            options: ["a) Neue Sachen kaufen", "b) Alte Sachen verkaufen", "c) Essen bestellen"],
            correct: "b",
          },
          {
            id: 4,
            text: "Babysitter gesucht!\nFur 2 Kinder (3 und 5 Jahre)\nFreitag und Samstag abends, 18:00 - 22:00\n12 Euro pro Stunde\nTelefon: 0221-5556789",
            question: "Wie viel verdient der Babysitter pro Stunde?",
            options: ["a) 5 Euro", "b) 12 Euro", "c) 22 Euro"],
            correct: "b",
          },
          {
            id: 5,
            text: "ACHTUNG HAUSORDNUNG\nRuhezeiten: 22:00 - 7:00 Uhr\nMusik: bitte leise nach 20:00\nHaustiere: nur mit Erlaubnis\nMulltrennung: Papier, Plastik, Bio",
            question: "Ab wann muss man leise sein?",
            options: ["a) Ab 20:00 Uhr", "b) Ab 22:00 Uhr", "c) Ab 7:00 Uhr"],
            correct: "b",
          },
        ],
      },
      teil2: {
        instruction: "Lesen Sie die Texte. Sind die Aussagen richtig oder falsch?",
        items: [
          {
            id: 6,
            text: "Nachricht: Liebe Nachbarn, am Samstag, den 3. Juni, machen wir ein Grillfest im Garten. Alle sind herzlich eingeladen! Bitte bringt Salat oder Getränke mit. Wir haben genug Fleisch und Wurst. Ab 16 Uhr geht es los! Familie Braun",
            question: "Die Nachbarn sollen Fleisch mitbringen.",
            options: ["richtig", "falsch"],
            correct: "falsch",
          },
          {
            id: 7,
            text: "Tanzschule SALSA Y MAS\nAnfängerkurs: jeden Donnerstag, 19:00 - 20:30\nKeine Vorkenntnisse notig!\nPartner/in nicht erforderlich\nErstes Training kostenlos",
            question: "Man braucht einen Tanzpartner für den Kurs.",
            options: ["richtig", "falsch"],
            correct: "falsch",
          },
          {
            id: 8,
            text: "E-Mail: Hallo Jan, ich habe zwei Karten für das Konzert am Freitag. Hast du Lust mitzukommen? Es fangt um 20 Uhr an. Wir können uns um 19:30 vor der Halle treffen. Sag mir bitte Bescheid! LG Sophie",
            question: "Sophie hat Konzertkarten.",
            options: ["richtig", "falsch"],
            correct: "richtig",
          },
          {
            id: 9,
            text: "Fahrschule EASY DRIVE\nFührerschein Klasse B (Auto)\nTheorie: Mo + Mi, 18:30 - 20:00\nPraxis: nach Vereinbarung\nGesamtpreis: ab 1.800 Euro\nRatenzahlung moglich",
            question: "Man kann den Führerschein in Raten bezahlen.",
            options: ["richtig", "falsch"],
            correct: "richtig",
          },
          {
            id: 10,
            text: "SMS: Hey Nina! Bin am Flughafen gelandet. Mein Flug hatte 2 Stunden Verspätung. Bin total mude. Komme mit der S-Bahn. Bin in ca. 45 Minuten da. Bis gleich! Kai",
            question: "Kai ist pünktlich gelandet.",
            options: ["richtig", "falsch"],
            correct: "falsch",
          },
        ],
      },
      teil3: {
        instruction: "Lesen Sie den Text und die Aufgaben. Kreuzen Sie die richtige Antwort an.",
        items: [
          {
            id: 11,
            text: "Mein Name ist Olga und ich bin 35 Jahre alt. Ich komme aus der Ukraine und lebe seit drei Jahren in Wien. Ich arbeite als Krankenschwester in einem großen Krankenhaus. Die Arbeit ist manchmal schwer, aber ich helfe gern Menschen. Ich arbeite oft am Wochenende und nachts. In meiner Freizeit gehe ich gern ins Museum oder ins Konzert. Wien hat viel Kultur! Ich wohne mit meinem Mann und unserer Tochter in einer kleinen Wohnung. Meine Tochter ist 7 und geht in die zweite Klasse. Sie spricht schon sehr gut Deutsch.",
            question: "Wo arbeitet Olga?",
            options: ["a) In einer Schule", "b) Im Krankenhaus", "c) In einem Museum"],
            correct: "b",
          },
          {
            id: 12,
            text: "Mein Name ist Olga und ich bin 35 Jahre alt. Ich komme aus der Ukraine und lebe seit drei Jahren in Wien. Ich arbeite als Krankenschwester in einem großen Krankenhaus. Die Arbeit ist manchmal schwer, aber ich helfe gern Menschen. Ich arbeite oft am Wochenende und nachts. In meiner Freizeit gehe ich gern ins Museum oder ins Konzert. Wien hat viel Kultur! Ich wohne mit meinem Mann und unserer Tochter in einer kleinen Wohnung. Meine Tochter ist 7 und geht in die zweite Klasse. Sie spricht schon sehr gut Deutsch.",
            question: "Olga arbeitet...",
            options: ["a) nur am Tag", "b) auch nachts und am Wochenende", "c) nur von Montag bis Freitag"],
            correct: "b",
          },
          {
            id: 13,
            text: "Mein Name ist Olga und ich bin 35 Jahre alt. Ich komme aus der Ukraine und lebe seit drei Jahren in Wien. Ich arbeite als Krankenschwester in einem großen Krankenhaus. Die Arbeit ist manchmal schwer, aber ich helfe gern Menschen. Ich arbeite oft am Wochenende und nachts. In meiner Freizeit gehe ich gern ins Museum oder ins Konzert. Wien hat viel Kultur! Ich wohne mit meinem Mann und unserer Tochter in einer kleinen Wohnung. Meine Tochter ist 7 und geht in die zweite Klasse. Sie spricht schon sehr gut Deutsch.",
            question: "Was macht Olga gern in der Freizeit?",
            options: ["a) Sport", "b) Ins Museum oder Konzert gehen", "c) Kochen"],
            correct: "b",
          },
          {
            id: 14,
            text: "Mein Name ist Olga und ich bin 35 Jahre alt. Ich komme aus der Ukraine und lebe seit drei Jahren in Wien. Ich arbeite als Krankenschwester in einem großen Krankenhaus. Die Arbeit ist manchmal schwer, aber ich helfe gern Menschen. Ich arbeite oft am Wochenende und nachts. In meiner Freizeit gehe ich gern ins Museum oder ins Konzert. Wien hat viel Kultur! Ich wohne mit meinem Mann und unserer Tochter in einer kleinen Wohnung. Meine Tochter ist 7 und geht in die zweite Klasse. Sie spricht schon sehr gut Deutsch.",
            question: "Mit wem lebt Olga zusammen?",
            options: ["a) Allein", "b) Mit Mann und Tochter", "c) Mit ihren Eltern"],
            correct: "b",
          },
          {
            id: 15,
            text: "Mein Name ist Olga und ich bin 35 Jahre alt. Ich komme aus der Ukraine und lebe seit drei Jahren in Wien. Ich arbeite als Krankenschwester in einem großen Krankenhaus. Die Arbeit ist manchmal schwer, aber ich helfe gern Menschen. Ich arbeite oft am Wochenende und nachts. In meiner Freizeit gehe ich gern ins Museum oder ins Konzert. Wien hat viel Kultur! Ich wohne mit meinem Mann und unserer Tochter in einer kleinen Wohnung. Meine Tochter ist 7 und geht in die zweite Klasse. Sie spricht schon sehr gut Deutsch.",
            question: "Olgas Tochter spricht...",
            options: ["a) kein Deutsch", "b) gut Deutsch", "c) nur Ukrainisch"],
            correct: "b",
          },
        ],
      },
    },
    schreiben: {
      teil1: {
        instruction: "Sie möchten sich bei einer Firma bewerben. Füllen Sie das Formular aus.",
        formTitle: "Bewerbung - Personliche Daten",
        fields: [
          { label: "Vor- und Nachname", answer: "", hint: "Ihr voller Name" },
          { label: "Geburtsdatum und -ort", answer: "", hint: "z.B. 15.03.1990, Ankara" },
          { label: "Staatsangehörigkeit", answer: "", hint: "z.B. türkisch" },
          { label: "Beruf / Ausbildung", answer: "", hint: "z.B. Verkaufer/in" },
          { label: "Deutschkenntnisse", answer: "", hint: "z.B. A1, Grundkenntnisse" },
        ],
      },
      teil2: {
        instruction: "Schreiben Sie eine kurze Nachricht (circa 30 Wörter).",
        situation: "Sie haben im Deutschkurs einen Kugelschreiber gefunden. Schreiben Sie eine Nachricht an den Kurs.",
        bullets: [
          "Was haben Sie gefunden?",
          "Wo haben Sie es gefunden?",
          "Was soll die Person tun?",
        ],
        minWords: 30,
      },
    },
    sprechen: {
      teil1: {
        teil: 1,
        instruction: "Sich vorstellen: Sagen Sie etwas über sich.",
        prompts: ["Name?", "Alter?", "Land?", "Wohnort?", "Sprachen?", "Beruf / Arbeit?", "Hobbys?"],
      },
      teil2: {
        teil: 2,
        instruction: "Über ein Thema sprechen: Stellen Sie Fragen und antworten Sie.",
        prompts: ["Arbeit: Was arbeiten Sie? Wie sind die Arbeitszeiten?", "Lernen: Wo lernen Sie Deutsch? Wie oft haben Sie Kurs?", "Kleidung: Was tragen Sie gern? Wo kaufen Sie Kleidung?", "Feste: Welche Feste feiern Sie? Was machen Sie an Weihnachten?"],
      },
      teil3: {
        teil: 3,
        instruction: "Bitten formulieren und darauf reagieren.",
        prompts: ["Sie haben den Bus verpasst. Fragen Sie jemanden, wann der nächste Bus kommt.", "Sie möchten ein Zimmer in einer WG mieten. Fragen Sie nach dem Preis und der Größe.", "Sie sind in einem Restaurant. Bitten Sie um die Speisekarte."],
      },
    },
  },
];
