import type { TelcTest } from './types';

export const testsA2: TelcTest[] = [
  // ============================================================
  //  A2 TEST 1
  // ============================================================
  {
    id: 4,
    level: 'A2',
    name: 'Übungstest 1',
    hoeren: {
      teil1: {
        instruction: 'Sie hören sechs kurze Gespräche. Zu jedem Gespräch gibt es eine Aufgabe. Kreuzen Sie die richtige Antwort an. Sie hören jeden Text zweimal.',
        replays: 2,
        items: [
          {
            id: 1,
            context: 'Im Büro — ein Anruf',
            audio: 'Stefan Müller spricht auf den Anrufbeantworter: Hallo, hier ist Stefan Müller. Ich bin leider krank und kann heute nicht kommen. Können Sie bitte meinen Kollegen Thomas informieren? Ich rufe morgen wieder an.',
            question: 'Warum ruft Herr Müller an?',
            options: ['a) Er möchte einen Termin vereinbaren', 'b) Er kann heute nicht zur Arbeit kommen', 'c) Er sucht seinen Kollegen Thomas'],
            correct: 'b',
          },
          {
            id: 2,
            context: 'In der Bäckerei',
            audio: 'Kundin: Ich hätte gerne drei Brötchen und ein Baguette. Verkäuferin: Die drei Brötchen kosten einen Euro fünfzig, das Baguette zwei Euro achtzig. Das macht zusammen vier Euro dreißig. Kundin: Hier sind fünf Euro. Verkäuferin: Und siebzig Cent zurück.',
            question: 'Was kostet alles zusammen?',
            options: ['a) drei Euro fünfzig', 'b) vier Euro dreißig', 'c) vier Euro achtzig'],
            correct: 'b',
          },
          {
            id: 3,
            context: 'Beim Zahnarzt — Terminvereinbarung',
            audio: 'Sprechstundenhilfe: Zahnarztpraxis Dr. Schmidt, guten Tag. Patient: Guten Tag, ich brauche dringend einen Termin. Ich habe starke Zahnschmerzen. Sprechstundenhilfe: Können Sie morgen um vierzehn Uhr kommen? Patient: Ja, das passt gut. Sprechstundenhilfe: Ihren Namen bitte? Patient: Müller, Wolfgang Müller.',
            question: 'Wann ist der Termin?',
            options: ['a) Heute um 14 Uhr', 'b) Morgen um 14 Uhr', 'c) Übermorgen um 10 Uhr'],
            correct: 'b',
          },
          {
            id: 4,
            context: 'Wettervorhersage im Radio',
            audio: 'Und jetzt das Wetter für morgen: Im Norden bleibt es bewölkt mit einzelnen Regenschauern. Temperaturen zwischen zwölf und sechzehn Grad. Im Süden scheint die Sonne und es wird warm. Temperaturen bis zweiundzwanzig Grad.',
            question: 'Wie ist das Wetter morgen im Süden?',
            options: ['a) Regen und kühl', 'b) bewölkt und warm', 'c) sonnig und warm'],
            correct: 'c',
          },
          {
            id: 5,
            context: 'Am Bahnhof — Durchsage',
            audio: 'Achtung auf Gleis drei: Der InterCity nach Hamburg Hauptbahnhof hat leider heute Verspätung. Der Zug kommt voraussichtlich fünfundzwanzig Minuten später an. Wir entschuldigen uns für die Unannehmlichkeiten. Bitte beachten Sie auch die aktuellen Informationen auf den Anzeigetafeln.',
            question: 'Was ist das Problem mit dem Zug nach Hamburg?',
            options: ['a) Er fährt von einem anderen Gleis ab', 'b) Er fällt heute aus', 'c) Er kommt später als geplant an'],
            correct: 'c',
          },
          {
            id: 6,
            context: 'Telefongespräch — Einladung zur Party',
            audio: 'Lea: Kommst du heute Abend zu Annas Party? Jonas: Ich weiß nicht... die Party beginnt erst um einundzwanzig Uhr, das ist mir zu spät. Lea: Schade! Morgen muss ich sehr früh aufstehen. Jonas: Ich auch, aber ich komme trotzdem kurz vorbei.',
            question: 'Warum möchte Jonas nicht zur Party?',
            options: ['a) Er ist krank', 'b) Die Party beginnt zu spät', 'c) Er muss morgen arbeiten'],
            correct: 'b',
          },
        ],
      },
      teil2: {
        instruction: 'Sie hören ein Gespräch. Lesen Sie die Aufgaben. Kreuzen Sie an: richtig oder falsch. Sie hören den Text einmal.',
        replays: 1,
        items: [
          {
            id: 7,
            context: 'Gespräch in einer Firma — Vorstellungsgespräch',
            audio: 'Personalchef: Guten Tag, Frau Klein, bitte setzen Sie sich. Frau Klein: Danke, guten Tag. Personalchef: Sie haben drei Jahre als Verkäuferin bei einem Supermarkt in München gearbeitet, richtig? Frau Klein: Ja, genau. Aber jetzt möchte ich ins Büro wechseln. Deshalb mache ich gerade einen Computerkurs am Abend. Personalchef: Sehr gut. Und wann könnten Sie bei uns anfangen? Frau Klein: Ab dem ersten nächsten Monats wäre ideal. Personalchef: Gut. Wir melden uns in der nächsten Woche bei Ihnen.',
            question: 'Frau Klein hat früher als Lehrerin gearbeitet.',
            options: ['richtig', 'falsch'],
            correct: 'falsch',
          },
          {
            id: 8,
            context: '',
            audio: '',
            question: 'Frau Klein macht zurzeit einen Computerkurs.',
            options: ['richtig', 'falsch'],
            correct: 'richtig',
          },
          {
            id: 9,
            context: '',
            audio: '',
            question: 'Frau Klein kann sofort anfangen.',
            options: ['richtig', 'falsch'],
            correct: 'falsch',
          },
          {
            id: 10,
            context: '',
            audio: '',
            question: 'Die Firma ruft nächste Woche an.',
            options: ['richtig', 'falsch'],
            correct: 'richtig',
          },
        ],
      },
      teil3: {
        instruction: 'Sie hören ein längeres Interview. Zu jedem Punkt gibt es eine Aufgabe. Kreuzen Sie die richtige Antwort an. Sie hören den Text einmal.',
        replays: 1,
        items: [
          {
            id: 11,
            context: 'Radio-Interview — Thema: Homeoffice',
            audio: 'Moderatorin: Herzlich willkommen! Heute sprechen wir über Homeoffice. Mein Gast ist Thomas Becker. Herr Becker arbeitet seit zwei Jahren von zu Hause. Herr Becker, wie war das am Anfang? Herr Becker: Ehrlich gesagt war es schwierig. Ich hatte Probleme, Arbeit und Freizeit zu trennen. Abends habe ich immer noch Mails geschrieben. Moderatorin: Was haben Sie dagegen gemacht? Herr Becker: Ich habe feste Arbeitszeiten eingeführt — von neun bis achtzehn Uhr. Danach ist der Computer aus. Moderatorin: Vermissen Sie Ihre Kollegen? Herr Becker: Manchmal ja. Deshalb treffe ich mich einmal pro Woche im Büro mit meinen Kollegen. Das ist gut für den Kontakt. Moderatorin: Würden Sie Homeoffice empfehlen? Herr Becker: Ja, aber man braucht Disziplin und einen ruhigen Arbeitsplatz. Ohne das funktioniert es nicht.',
            question: 'Wie lange arbeitet Herr Becker schon im Homeoffice?',
            options: ['a) Ein Jahr', 'b) Zwei Jahre', 'c) Drei Jahre'],
            correct: 'b',
          },
          {
            id: 12,
            context: '',
            audio: '',
            question: 'Was war am Anfang schwierig?',
            options: ['a) Der Computer funktionierte nicht', 'b) Er schrieb abends noch Mails', 'c) Kollegen riefen zu oft an'],
            correct: 'b',
          },
          {
            id: 13,
            context: '',
            audio: '',
            question: 'Bis wann arbeitet Herr Becker täglich?',
            options: ['a) bis siebzehn Uhr', 'b) bis achtzehn Uhr', 'c) bis zwanzig Uhr'],
            correct: 'b',
          },
          {
            id: 14,
            context: '',
            audio: '',
            question: 'Wie oft trifft er seine Kollegen im Büro?',
            options: ['a) täglich', 'b) einmal pro Woche', 'c) zweimal pro Monat'],
            correct: 'b',
          },
          {
            id: 15,
            context: '',
            audio: '',
            question: 'Was braucht man laut Herrn Becker für Homeoffice?',
            options: ['a) Schnelles Internet und einen Drucker', 'b) Einen großen Schreibtisch', 'c) Disziplin und einen ruhigen Arbeitsplatz'],
            correct: 'c',
          },
        ],
      },
    },
    lesen: {
      teil1: {
        instruction: 'Lesen Sie die fünf Texte. Welche Antwort passt? Kreuzen Sie an.',
        items: [
          {
            id: 1,
            text: 'STELLENANZEIGE: Wir suchen eine freundliche Rezeptionistin (m/w/d) für unser Hotel im Stadtzentrum. Erfahrung im Kundenkontakt erwünscht. Englischkenntnisse notwendig. Vollzeit (40 Stunden/Woche). Bewerbungen bitte per E-Mail an jobs@stadthotel.de',
            question: 'Was sucht das Hotel?',
            options: ['a) Eine Köchin mit Englischkenntnissen', 'b) Eine Mitarbeiterin für die Rezeption', 'c) Eine Zimmermädchen in Teilzeit'],
            correct: 'b',
          },
          {
            id: 2,
            text: 'HINWEIS AN ALLE MIETER: Das Treppenhaus und der Aufzug werden am Donnerstag, 15. April, von 8 bis 14 Uhr gereinigt. Bitte benutzen Sie in dieser Zeit die Treppe. Der Aufzug ist gesperrt. Vielen Dank für Ihr Verständnis. — Die Hausverwaltung',
            question: 'Was passiert am 15. April?',
            options: ['a) Das Treppenhaus wird gebaut', 'b) Der Aufzug wird repariert', 'c) Das Gebäude wird gereinigt'],
            correct: 'c',
          },
          {
            id: 3,
            text: 'Liebe Nachbarin, ich fahre vom 20. bis 28. Juli in den Urlaub. Könntest du zweimal pro Woche meinen Blumen gießen? Sie stehen auf dem Balkon. Den Schlüssel habe ich unter der Fußmatte gelassen. Ich bringe dir ein Souvenir mit! Herzliche Grüße, Maria',
            question: 'Was soll die Nachbarin tun?',
            options: ['a) Den Briefkasten leeren', 'b) Die Blumen gießen', 'c) Die Wohnung aufräumen'],
            correct: 'b',
          },
          {
            id: 4,
            text: 'STADTBIBLIOTHEK — Neue Öffnungszeiten ab 1. September: Montag – Freitag: 10:00 – 19:00 Uhr, Samstag: 10:00 – 14:00 Uhr. Die Bibliothek ist sonntags und an Feiertagen geschlossen. Bücher können auch online verlängert werden: www.stadtbib.de',
            question: 'Wann ist die Bibliothek am Samstag geöffnet?',
            options: ['a) Von 10 bis 19 Uhr', 'b) Von 10 bis 14 Uhr', 'c) Sie ist samstags geschlossen'],
            correct: 'b',
          },
          {
            id: 5,
            text: 'FAHRSCHULE SCHMIDT — Sonderangebot: Intensivkurs Führerschein Klasse B. In nur 3 Wochen zum Führerschein! Alle Fahrstunden inklusive. Theorieunterricht online. Preis: 1.850 € (statt 2.200 €). Anmeldung unter: 089 / 44 33 22',
            question: 'Was bietet die Fahrschule an?',
            options: ['a) Einen günstigen Motorradkurs', 'b) Kostenlose Fahrstunden', 'c) Einen Intensivkurs für den Führerschein'],
            correct: 'c',
          },
        ],
      },
      teil2: {
        instruction: 'Lesen Sie den Text. Sind die Aussagen richtig oder falsch?',
        items: [
          {
            id: 6,
            text: 'Immer mehr Menschen kaufen ihre Lebensmittel online. Supermärkte und spezialisierte Lieferdienste bringen die Einkäufe direkt nach Hause. Das ist besonders praktisch für Menschen, die wenig Zeit haben oder nicht gut zu Fuß sind. Allerdings haben viele Kunden das Problem, dass sie beim Online-Kauf die Qualität von Obst und Gemüse nicht sehen können. Außerdem fallen oft zusätzliche Lieferkosten an. Trotzdem: Laut einer aktuellen Studie bestellen bereits 35 Prozent der Deutschen mindestens einmal pro Monat Lebensmittel online.',
            question: 'Online-Einkauf ist besonders gut für Menschen, die wenig Zeit haben.',
            options: ['richtig', 'falsch'],
            correct: 'richtig',
          },
          {
            id: 7,
            text: '',
            question: 'Beim Online-Kauf kann man die Qualität von Obst und Gemüse gut prüfen.',
            options: ['richtig', 'falsch'],
            correct: 'falsch',
          },
          {
            id: 8,
            text: '',
            question: 'Online-Einkauf ist immer kostenlos.',
            options: ['richtig', 'falsch'],
            correct: 'falsch',
          },
          {
            id: 9,
            text: '',
            question: 'Mehr als ein Drittel der Deutschen kaufen manchmal Lebensmittel online.',
            options: ['richtig', 'falsch'],
            correct: 'richtig',
          },
          {
            id: 10,
            text: '',
            question: 'Nur ältere Menschen kaufen Lebensmittel online.',
            options: ['richtig', 'falsch'],
            correct: 'falsch',
          },
        ],
      },
      teil3: {
        instruction: 'Lesen Sie den Text und die Aufgaben. Welche Antwort passt?',
        items: [
          {
            id: 11,
            text: 'INTERVIEW: "Ich lebe seit drei Jahren in Deutschland"\nKarim Mansour ist 28 Jahre alt und kommt aus Tunesien. Er ist vor drei Jahren nach München gekommen, um Ingenieurwesen zu studieren. "Am Anfang war die Sprache das größte Problem", erzählt er. "Ich habe zwar in der Schule Deutsch gelernt, aber das Sprechen mit echten Menschen war viel schwieriger als erwartet." Heute spricht Karim fließend Deutsch. Er macht bald seinen Bachelor-Abschluss und hat schon ein Praktikumsangebot von einer deutschen Firma. "Was ich am meisten vermisse, ist das Essen meiner Mutter", sagt er lächelnd. "Aber ich habe hier viele neue Freunde gefunden und fühle mich sehr wohl."',
            question: 'Warum ist Karim nach München gekommen?',
            options: ['a) Um zu arbeiten', 'b) Um zu studieren', 'c) Um Deutsch zu lernen'],
            correct: 'b',
          },
          {
            id: 12,
            text: '',
            question: 'Was war am Anfang sein größtes Problem?',
            options: ['a) Er hatte keine Freunde', 'b) Das Wetter in München', 'c) Die deutsche Sprache'],
            correct: 'c',
          },
          {
            id: 13,
            text: '',
            question: 'Was hat Karim bald nach dem Studium?',
            options: ['a) Ein Praktikum bei einer deutschen Firma', 'b) Eine feste Stelle als Ingenieur', 'c) Ein Stipendium für weitere Studien'],
            correct: 'a',
          },
          {
            id: 14,
            text: '',
            question: 'Was vermisst Karim am meisten?',
            options: ['a) Seine Stadt in Tunesien', 'b) Das Essen seiner Mutter', 'c) Seine alten Schulfreunde'],
            correct: 'b',
          },
          {
            id: 15,
            text: '',
            question: 'Wie fühlt sich Karim heute in München?',
            options: ['a) Er fühlt sich noch fremd', 'b) Er möchte zurück nach Tunesien', 'c) Er fühlt sich wohl'],
            correct: 'c',
          },
        ],
      },
    },
    schreiben: {
      teil1: {
        instruction: 'Lesen Sie die Informationen. Füllen Sie das Formular aus.',
        formTitle: 'Anmeldung für einen Sprachkurs',
        personCard: [
          'Name: Sandra Hoffmann',
          'Geburtsdatum: 14.03.1990',
          'Nationalität: Österreichisch',
          'Adresse: Schillerstraße 22, 80336 München',
          'Telefon: 0173 / 456 78 90',
          'E-Mail: s.hoffmann@gmx.at',
          'Bereits besuchte Kurse: Englisch B2 (2019)',
          'Gewünschter Kurs: Spanisch, Anfänger (A1)',
        ],
        fields: [
          { label: 'Vorname und Nachname', answer: 'Sandra Hoffmann', hint: 'Vollständiger Name' },
          { label: 'Geburtsdatum', answer: '14.03.1990', hint: 'TT.MM.JJJJ' },
          { label: 'Nationalität', answer: 'Österreichisch' },
          { label: 'E-Mail-Adresse', answer: 's.hoffmann@gmx.at' },
          { label: 'Gewünschter Kurs', answer: 'Spanisch A1', hint: 'Sprache und Niveau' },
        ],
      },
      teil2: {
        instruction: 'Sie haben eine E-Mail von Ihrer Freundin bekommen. Schreiben Sie eine Antwort.',
        situation: 'Ihre Freundin Lisa schreibt: "Ich habe nächsten Samstag Geburtstag und mache eine kleine Party. Kannst du kommen? Wir essen zusammen und hören Musik. Bring gerne etwas zu trinken mit!"',
        bullets: [
          'Danken Sie für die Einladung',
          'Sagen Sie, ob Sie kommen können',
          'Fragen Sie, um wie viel Uhr die Party beginnt',
          'Schreiben Sie, was Sie mitbringen',
        ],
        minWords: 50,
      },
    },
    sprechen: {
      teil1: {
        teil: 1,
        instruction: 'Stellen Sie sich vor. Sprechen Sie über sich selbst: Woher kommen Sie? Wo wohnen Sie? Was machen Sie beruflich oder was studieren Sie? Was sind Ihre Hobbys?',
        prompts: [
          'Name und Herkunft',
          'Wohnort',
          'Beruf oder Studium',
          'Hobbys und Interessen',
          'Warum lernen Sie Deutsch?',
        ],
        exampleResponse: 'Ich heiße... und komme aus... Ich wohne seit... Jahren in... Ich arbeite als... / Ich studiere... In meiner Freizeit... Ich lerne Deutsch, weil...',
      },
      teil2: {
        teil: 2,
        instruction: 'Sie sehen eine Situation. Machen Sie einen Vorschlag oder bitten Sie um etwas. Reagieren Sie auf Ihren Gesprächspartner.',
        prompts: [
          'Sie möchten mit einem Freund ins Kino gehen. Wählen Sie einen Film und eine Uhrzeit.',
          'Ihr Freund kann am Freitag nicht. Schlagen Sie einen anderen Tag vor.',
          'Fragen Sie, wie ihr Freund zum Kino kommen möchte.',
          'Verabreden Sie sich an einem Treffpunkt.',
        ],
        exampleResponse: 'Hast du Lust, am... ins Kino zu gehen? Ich habe an... frei. Wollen wir uns um... Uhr treffen?',
      },
      teil3: {
        teil: 3,
        instruction: 'Sie sehen ein Bild einer Alltagssituation. Beschreiben Sie das Bild und antworten Sie auf Fragen dazu.',
        prompts: [
          'Beschreiben Sie: Was sehen Sie auf dem Bild? (Menschen beim Einkaufen im Supermarkt)',
          'Was kaufen die Menschen wahrscheinlich?',
          'Gehen Sie lieber in ein Geschäft oder kaufen Sie lieber online ein? Warum?',
          'Was kaufen Sie regelmäßig ein?',
        ],
      },
    },
  },

  // ============================================================
  //  A2 TEST 2
  // ============================================================
  {
    id: 5,
    level: 'A2',
    name: 'Übungstest 2',
    hoeren: {
      teil1: {
        instruction: 'Sie hören sechs kurze Gespräche. Zu jedem Gespräch gibt es eine Aufgabe. Kreuzen Sie die richtige Antwort an. Sie hören jeden Text zweimal.',
        replays: 2,
        items: [
          {
            id: 1,
            context: 'Im Sportverein',
            audio: 'Trainerin: Hallo Lisa, du warst letzte Woche nicht beim Training. Alles okay? Lisa: Ja, danke. Ich hatte Grippe. Bin aber jetzt wieder fit. Trainerin: Gut! Das nächste Training ist Dienstag um siebzehn Uhr. Sei bitte pünktlich.',
            question: 'Warum war Lisa nicht beim Training?',
            options: ['a) Sie hatte keine Zeit', 'b) Sie war krank', 'c) Sie war im Urlaub'],
            correct: 'b',
          },
          {
            id: 2,
            context: 'Am Telefon — Reservierung',
            audio: 'Rezeptionist: Hotel Stadtpark, guten Tag. Gast: Guten Tag. Ich möchte ein Zimmer reservieren, bitte. Für den fünfzehnten bis siebzehnten März. Rezeptionist: Das sind zwei Nächte. Ein Einzelzimmer oder Doppelzimmer? Gast: Doppelzimmer bitte, mit Frühstück. Rezeptionist: Kein Problem, ich trage Sie ein.',
            question: 'Wie viele Nächte möchte der Gast bleiben?',
            options: ['a) Eine Nacht', 'b) Zwei Nächte', 'c) Drei Nächte'],
            correct: 'b',
          },
          {
            id: 3,
            context: 'Auf dem Markt',
            audio: 'Kunde: Haben Sie frische Erdbeeren? Verkäuferin: Ja, ein Kilo kostet drei Euro fünfzig. Die kommen direkt vom Bauern. Kunde: Gut, ich nehme zwei Kilo. Dazu noch ein Pfund Tomaten bitte. Verkäuferin: Natürlich. Die Tomaten kosten zwei Euro das Pfund.',
            question: 'Was kostet ein Kilo Erdbeeren?',
            options: ['a) zwei Euro', 'b) drei Euro fünfzig', 'c) fünf Euro'],
            correct: 'b',
          },
          {
            id: 4,
            context: 'In der Apotheke',
            audio: 'Apothekerin: Kann ich Ihnen helfen? Kunde: Ja, ich brauche etwas gegen Kopfschmerzen. Ich habe heute Morgen schon zwei Aspirin genommen, aber es hilft nicht. Apothekerin: Dann empfehle ich Ihnen dieses stärkere Mittel. Nehmen Sie es mit viel Wasser und nicht auf leeren Magen.',
            question: 'Was empfiehlt die Apothekerin?',
            options: ['a) Mehr Aspirin zu nehmen', 'b) Zum Arzt zu gehen', 'c) Ein stärkeres Medikament'],
            correct: 'c',
          },
          {
            id: 5,
            context: 'Im Restaurant',
            audio: 'Kellner: Kann ich Ihnen helfen? Gast: Ja, ich möchte bestellen. Ich nehme die Gemüsesuppe als Vorspeise und dann das Schnitzel mit Pommes als Hauptgericht. Kellner: Und zu trinken? Gast: Ein großes Wasser bitte. Ohne Kohlensäure.',
            question: 'Was bestellt der Gast als Hauptspeise?',
            options: ['a) Gemüsesuppe', 'b) Schnitzel mit Pommes', 'c) Salat und Suppe'],
            correct: 'b',
          },
          {
            id: 6,
            context: 'Gespräch zwischen Freunden',
            audio: 'Anna: Ich habe nächste Woche Prüfung und lerne den ganzen Tag. Ben: Für welches Fach? Anna: Mathematik. Ich bin schon ganz gestresst. Ben: Soll ich dir helfen? Ich bin gut in Mathe. Anna: Wirklich? Das wäre super! Können wir uns morgen Nachmittag treffen?',
            question: 'Warum ist Anna gestresst?',
            options: ['a) Sie hat Probleme mit Freunden', 'b) Sie hat eine Mathematikprüfung', 'c) Sie muss viel arbeiten'],
            correct: 'b',
          },
        ],
      },
      teil2: {
        instruction: 'Sie hören eine Radiosendung. Sind die Aussagen richtig oder falsch?',
        replays: 1,
        items: [
          {
            id: 7,
            context: 'Radiosendung über Fahrradfahren in der Stadt',
            audio: 'Moderator: Heute sprechen wir über das Thema Fahrrad in der Stadt. In vielen deutschen Städten gibt es immer mehr Radwege. In München zum Beispiel sind in den letzten fünf Jahren hundert Kilometer neue Radwege gebaut worden. Das Fahrrad ist nicht nur gut für die Umwelt, sondern auch günstiger als das Auto. Eine aktuelle Studie zeigt: Wer täglich mit dem Fahrrad zur Arbeit fährt, spart im Jahr durchschnittlich zweitausend Euro. Außerdem bleiben Radfahrer gesünder — sie sind seltener krank als Autofahrer. Der einzige Nachteil: Bei schlechtem Wetter ist Radfahren nicht so angenehm.',
            question: 'In München wurden in fünf Jahren hundert Kilometer neue Radwege gebaut.',
            options: ['richtig', 'falsch'],
            correct: 'richtig',
          },
          {
            id: 8,
            context: '',
            audio: '',
            question: 'Das Fahrrad ist teurer als das Auto.',
            options: ['richtig', 'falsch'],
            correct: 'falsch',
          },
          {
            id: 9,
            context: '',
            audio: '',
            question: 'Radfahrer sparen jährlich etwa zweitausend Euro.',
            options: ['richtig', 'falsch'],
            correct: 'richtig',
          },
          {
            id: 10,
            context: '',
            audio: '',
            question: 'Radfahrer sind öfter krank als Autofahrer.',
            options: ['richtig', 'falsch'],
            correct: 'falsch',
          },
        ],
      },
      teil3: {
        instruction: 'Sie hören ein Interview. Zu jedem Punkt gibt es eine Aufgabe. Kreuzen Sie an.',
        replays: 1,
        items: [
          {
            id: 11,
            context: 'Interview mit einer Reisebloggerin',
            audio: 'Journalistin: Guten Tag, Frau Weber! Sie reisen viel. Wie viele Länder haben Sie schon besucht? Frau Weber: Ich habe bisher achtunddreißig Länder bereist. Journalistin: Wow! Welches Land hat Ihnen am besten gefallen? Frau Weber: Japan. Die Kultur ist so anders als in Europa, und die Menschen sind sehr freundlich. Journalistin: Und welches Reiseziel war enttäuschend? Frau Weber: Eigentlich war ich nirgends wirklich enttäuscht. Aber manche Orte sind viel touristischer als ich dachte. Journalistin: Wie finanzieren Sie Ihre Reisen? Frau Weber: Durch meinen Blog und Werbeverträge. Journalistin: Was empfehlen Sie für Leute, die günstig reisen möchten? Frau Weber: Früh buchen und flexibel beim Datum sein. Manchmal ist ein Flug am Dienstag viel günstiger als am Freitag.',
            question: 'Wie viele Länder hat Frau Weber besucht?',
            options: ['a) Achtzehn', 'b) Achtundzwanzig', 'c) Achtunddreißig'],
            correct: 'c',
          },
          {
            id: 12,
            context: '',
            audio: '',
            question: 'Welches Land hat ihr am besten gefallen?',
            options: ['a) Japan', 'b) China', 'c) Korea'],
            correct: 'a',
          },
          {
            id: 13,
            context: '',
            audio: '',
            question: 'Wie verdient sie Geld für ihre Reisen?',
            options: ['a) Durch ihren normalen Job', 'b) Durch Blog und Werbeverträge', 'c) Durch Reiseführer schreiben'],
            correct: 'b',
          },
          {
            id: 14,
            context: '',
            audio: '',
            question: 'Was empfiehlt sie für günstige Reisen?',
            options: ['a) Im Sommer reisen', 'b) Mit dem Zug fahren', 'c) Früh buchen und flexibel sein'],
            correct: 'c',
          },
          {
            id: 15,
            context: '',
            audio: '',
            question: 'Wann sind Flüge manchmal günstiger?',
            options: ['a) Am Wochenende', 'b) Am Dienstag', 'c) Am Freitag'],
            correct: 'b',
          },
        ],
      },
    },
    lesen: {
      teil1: {
        instruction: 'Lesen Sie die fünf Texte. Welche Antwort passt?',
        items: [
          {
            id: 1,
            text: 'BEKANNTMACHUNG: Wegen Umbauarbeiten ist das Stadtbad Mitte vom 1. bis 30. August geschlossen. In dieser Zeit können Sie das Freibad Nord (U-Bahn: Nordpark) oder das Hallenbad Süd (Bus 48) benutzen. Jahreskarten behalten ihre Gültigkeit.',
            question: 'Was können Schwimmer im August tun?',
            options: ['a) Das Stadtbad Mitte wie gewohnt nutzen', 'b) Ein anderes Schwimmbad besuchen', 'c) Ihre Jahreskarte zurückgeben'],
            correct: 'b',
          },
          {
            id: 2,
            text: 'Hallo Markus! Ich bin leider noch im Büro und werde es nicht rechtzeitig schaffen. Kannst du bitte die Kinder von der Schule abholen? Sie warten um 15 Uhr am Haupteingang. Ich bin spätestens um 17 Uhr zu Hause. Kauf bitte noch Milch und Brot. Danke! Veronika',
            question: 'Was soll Markus tun?',
            options: ['a) Veronika vom Büro abholen', 'b) Die Kinder von der Schule holen und einkaufen', 'c) Die Kinder um 17 Uhr abholen'],
            correct: 'b',
          },
          {
            id: 3,
            text: 'ACHTUNG BAUSTELLE: Die Hauptstraße ist zwischen Postplatz und Marktplatz vom 5. bis 25. September gesperrt. Bitte benutzen Sie die Umleitung über die Nebenstraße. Die Bushaltestelle "Rathaus" wird vorübergehend auf den Parkplatz Süd verlegt.',
            question: 'Was ist wegen der Baustelle geändert?',
            options: ['a) Die Hauptstraße ist dauerhaft gesperrt', 'b) Busse fahren eine andere Route', 'c) Der Parkplatz Süd ist gesperrt'],
            correct: 'b',
          },
          {
            id: 4,
            text: 'KOCHKURS — Mediterrane Küche\nLernen Sie leckere Gerichte aus Italien, Spanien und Griechenland! Jeden Mittwoch, 18:30 – 21:00 Uhr. 8 Termine. Kursgebühr: 160 Euro (inkl. Zutaten). Maximal 10 Teilnehmer. Anmeldung: VHS-Zentrum, Tel. 089-123456',
            question: 'Was ist im Kurspreis enthalten?',
            options: ['a) Nur der Unterricht', 'b) Unterricht und die Zutaten', 'c) Unterricht und ein Kochbuch'],
            correct: 'b',
          },
          {
            id: 5,
            text: 'ZU VERMIETEN: Gemütliche 2-Zimmer-Wohnung, 58 m², 2. Obergeschoss mit Aufzug, ruhige Lage. Einbauküche, Balkon, Tiefgaragenstellplatz. Kaltmiete: 850 €/Monat + 180 € Nebenkosten. Keine Haustiere. Kontakt: immobilien@muenchen.de',
            question: 'Was ist bei der Wohnung dabei?',
            options: ['a) Eine möblierte Wohnung mit allem', 'b) Küche, Balkon und Garagenplatz', 'c) Ein Garten und eine Terrasse'],
            correct: 'b',
          },
        ],
      },
      teil2: {
        instruction: 'Lesen Sie den Text und entscheiden Sie: richtig oder falsch?',
        items: [
          {
            id: 6,
            text: 'REISEBERICHT: Mein Wochenende in Hamburg\nLetztes Wochenende bin ich nach Hamburg gefahren. Die Reise mit dem Zug dauerte ungefähr vier Stunden. Ich habe bei einem Freund geschlafen, das hat mir viel Geld gespart. Am Samstag haben wir den Hafen besichtigt und eine Hafenrundfahrt gemacht. Das war sehr beeindruckend — Hamburg ist die zweitgrößte Stadt Deutschlands. Am Abend waren wir in einem kleinen Restaurant in der Speicherstadt. Am Sonntag habe ich den Fischmarkt besucht, der findet schon ab fünf Uhr morgens statt. Um achtzehn Uhr war ich wieder zu Hause. Ein tolles Wochenende!',
            question: 'Die Zugfahrt nach Hamburg dauerte ungefähr vier Stunden.',
            options: ['richtig', 'falsch'],
            correct: 'richtig',
          },
          {
            id: 7,
            text: '',
            question: 'Die Person hat in einem Hotel geschlafen.',
            options: ['richtig', 'falsch'],
            correct: 'falsch',
          },
          {
            id: 8,
            text: '',
            question: 'Hamburg ist die größte Stadt Deutschlands.',
            options: ['richtig', 'falsch'],
            correct: 'falsch',
          },
          {
            id: 9,
            text: '',
            question: 'Der Hamburger Fischmarkt beginnt sehr früh am Morgen.',
            options: ['richtig', 'falsch'],
            correct: 'richtig',
          },
          {
            id: 10,
            text: '',
            question: 'Die Person war zwei Nächte in Hamburg.',
            options: ['richtig', 'falsch'],
            correct: 'richtig',
          },
        ],
      },
      teil3: {
        instruction: 'Lesen Sie den Text und die Aufgaben. Welche Antwort passt?',
        items: [
          {
            id: 11,
            text: 'DIE DEUTSCHEN UND DER URLAUB\nDie Deutschen lieben den Urlaub — das belegen aktuelle Zahlen. Im Jahr 2023 haben rund 70 Prozent der Deutschen mindestens eine Reise unternommen. Das beliebteste Reiseziel war nach wie vor Deutschland selbst: Die Ostsee und Bayern stehen ganz oben auf der Liste. Im Ausland ist die Türkei seit Jahren eines der meistbesuchten Ziele, gefolgt von Spanien und Griechenland.\nInteressant ist, dass immer mehr Deutsche Städtereisen bevorzugen. Wien, Prag und Barcelona sind besonders beliebt. Der Trend zum Kurzurlaub — drei bis vier Tage — nimmt zu, während der klassische "Drei-Wochen-Urlaub" seltener wird. Viele Deutsche nutzen Feiertage, um lange Wochenenden zu verlängern.',
            question: 'Wie viele Deutsche haben 2023 mindestens eine Reise gemacht?',
            options: ['a) Etwa die Hälfte', 'b) Etwa 70 Prozent', 'c) Fast alle'],
            correct: 'b',
          },
          {
            id: 12,
            text: '',
            question: 'Was ist das beliebteste Reiseziel der Deutschen?',
            options: ['a) Die Türkei', 'b) Spanien', 'c) Deutschland selbst'],
            correct: 'c',
          },
          {
            id: 13,
            text: '',
            question: 'Welches Auslandsziel ist nach der Türkei am beliebtesten?',
            options: ['a) Griechenland', 'b) Spanien', 'c) Italien'],
            correct: 'b',
          },
          {
            id: 14,
            text: '',
            question: 'Welcher Trend ist bei Deutschen erkennbar?',
            options: ['a) Immer längere Urlaube', 'b) Mehr Kreuzfahrten', 'c) Mehr Kurzurlaube'],
            correct: 'c',
          },
          {
            id: 15,
            text: '',
            question: 'Was machen viele Deutsche mit Feiertagen?',
            options: ['a) Sie arbeiten trotzdem', 'b) Sie verlängern das Wochenende', 'c) Sie fahren ins Ausland'],
            correct: 'b',
          },
        ],
      },
    },
    schreiben: {
      teil1: {
        instruction: 'Lesen Sie die Informationen. Füllen Sie das Formular aus.',
        formTitle: 'Mitgliedschaftsantrag — Fitnessstudio PowerFit',
        personCard: [
          'Name: David Schneider',
          'Geburtsdatum: 07.11.1995',
          'Beruf: Krankenpfleger',
          'Adresse: Rosenweg 8, 50667 Köln',
          'Telefon: 0221 / 987 654',
          'Gewünschte Mitgliedschaft: Premium (12 Monate)',
          'Besondere Wünsche: Personal Training, montags und mittwochs',
        ],
        fields: [
          { label: 'Vollständiger Name', answer: 'David Schneider' },
          { label: 'Geburtsdatum', answer: '07.11.1995', hint: 'TT.MM.JJJJ' },
          { label: 'Beruf', answer: 'Krankenpfleger' },
          { label: 'Mitgliedschaftstyp', answer: 'Premium (12 Monate)' },
          { label: 'Gewünschte Trainingszeiten', answer: 'Montags und mittwochs', hint: 'Wochentage' },
        ],
      },
      teil2: {
        instruction: 'Schreiben Sie eine kurze Nachricht.',
        situation: 'Ihr Kollege Marco hat Ihnen eine E-Mail geschrieben: "Ich muss nächste Woche zum Arzt und kann den Dienstagstermin mit dem Kunden nicht wahrnehmen. Könntest du einspringen? Der Termin ist um 10 Uhr im Büro."',
        bullets: [
          'Sagen Sie, ob Sie helfen können',
          'Fragen Sie, um welchen Kunden es sich handelt',
          'Fragen Sie, ob Sie Unterlagen bekommen können',
          'Wünschen Sie gute Besserung',
        ],
        minWords: 50,
      },
    },
    sprechen: {
      teil1: {
        teil: 1,
        instruction: 'Erzählen Sie von sich. Sprechen Sie über Ihren Alltag, Ihre Familie und Ihre Pläne für die Zukunft.',
        prompts: [
          'Wie sieht Ihr typischer Tag aus?',
          'Erzählen Sie von Ihrer Familie',
          'Was sind Ihre Zukunftspläne?',
          'Was haben Sie letztes Wochenende gemacht?',
        ],
        exampleResponse: 'Mein typischer Tag beginnt um... Ich frühstücke und dann... Meine Familie besteht aus... In der Zukunft möchte ich...',
      },
      teil2: {
        teil: 2,
        instruction: 'Sie möchten gemeinsam etwas planen. Diskutieren Sie und einigen Sie sich.',
        prompts: [
          'Schlagen Sie einen Ausflug in die Natur vor',
          'Diskutieren Sie das Ziel (Berg, See, Wald)',
          'Wie kommen Sie hin? (Auto, Fahrrad, Bus)',
          'Was nehmen Sie mit? (Essen, Getränke, Karte)',
        ],
      },
      teil3: {
        teil: 3,
        instruction: 'Geben Sie Informationen und reagieren Sie auf Fragen.',
        prompts: [
          'Beschreiben Sie Ihre Wohngegend',
          'Was gefällt Ihnen dort? Was nicht?',
          'Was würden Sie ändern, wenn Sie könnten?',
          'Vergleichen Sie mit einem anderen Ort, den Sie kennen',
        ],
      },
    },
  },

  // ============================================================
  //  A2 TEST 3
  // ============================================================
  {
    id: 6,
    level: 'A2',
    name: 'Übungstest 3',
    hoeren: {
      teil1: {
        instruction: 'Sie hören sechs kurze Gespräche. Kreuzen Sie die richtige Antwort an. Sie hören jeden Text zweimal.',
        replays: 2,
        items: [
          {
            id: 1,
            context: 'Am Telefon — Kundenservice',
            audio: 'Kundenservice: Kundenservice Müller GmbH, guten Tag. Kundin: Guten Tag. Ich habe vor zwei Wochen einen Laptop bestellt, aber er ist noch nicht angekommen. Kundenservice: Können Sie mir Ihre Bestellnummer nennen? Kundin: Ja, die ist A-2-3-4-5. Kundenservice: Ich schaue kurz nach... Ihr Paket war leider bei der Lieferung beschädigt und wird neu verschickt. Es kommt in drei bis fünf Tagen.',
            question: 'Warum hat die Kundin noch keinen Laptop erhalten?',
            options: ['a) Die Bestellung wurde storniert', 'b) Das Paket war beschädigt', 'c) Die Adresse war falsch'],
            correct: 'b',
          },
          {
            id: 2,
            context: 'Im Supermarkt',
            audio: 'Kind: Mama, kann ich diese Schokolade kaufen? Mutter: Nein, wir haben zu Hause noch Schokolade. Kind: Aber die ist anders! Mutter: Wir kaufen heute nur, was auf dem Einkaufszettel steht. Wir brauchen Milch, Butter und Mehl. Komm, wir müssen noch zur Kasse.',
            question: 'Was kauft die Mutter heute?',
            options: ['a) Schokolade und Milch', 'b) Nur was auf dem Zettel steht', 'c) Alles was das Kind möchte'],
            correct: 'b',
          },
          {
            id: 3,
            context: 'An der Universität',
            audio: 'Studentin: Entschuldigung, wissen Sie wo Raum 204 ist? Ich suche den Informatikkurs. Professor: Der Kurs ist heute ausnahmsweise in Raum 108 im Erdgeschoss. Der normale Raum wird gerade renoviert. Studentin: Oh, danke! Und wissen Sie, wann der Kurs beginnt? Professor: Um dreizehn Uhr dreißig.',
            question: 'Warum ist der Kurs in einem anderen Raum?',
            options: ['a) Der Professor ist neu', 'b) Der normale Raum wird renoviert', 'c) Es gibt zu viele Studenten'],
            correct: 'b',
          },
          {
            id: 4,
            context: 'Gespräch zwischen Kollegen',
            audio: 'Kollegin A: Warst du gestern bei der Firmenpräsentation? Kollegin B: Nein, ich musste früher gehen, meine Tochter war krank. Wie war es? Kollegin A: Sehr interessant! Der Chef hat angekündigt, dass wir bald ein neues Büro in Hamburg bekommen. Kollegin B: Wirklich? Das ist eine große Neuigkeit.',
            question: 'Was hat der Chef angekündigt?',
            options: ['a) Neue Mitarbeiter werden eingestellt', 'b) Ein neues Büro in Hamburg', 'c) Eine Gehaltserhöhung'],
            correct: 'b',
          },
          {
            id: 5,
            context: 'Stadtführung',
            audio: 'Stadtführer: Willkommen in der Altstadt! Auf der linken Seite sehen Sie das Rathaus, das im vierzehnten Jahrhundert gebaut wurde. Geradeaus ist die berühmte Marktkirche — sie ist jeden Tag von neun bis achtzehn Uhr geöffnet. Jetzt gehen wir zum Stadtpark, der nur fünf Minuten zu Fuß entfernt ist.',
            question: 'Wann ist die Marktkirche geöffnet?',
            options: ['a) Von 8 bis 17 Uhr', 'b) Von 9 bis 18 Uhr', 'c) Von 10 bis 20 Uhr'],
            correct: 'b',
          },
          {
            id: 6,
            context: 'Im Café',
            audio: 'Gast: Entschuldigung, ich warte jetzt schon dreißig Minuten auf meinen Kaffee. Kellnerin: Oh, tut mir leid! Es ist heute sehr voll und wir haben Personalmangel. Ich bringe Ihnen den Kaffee sofort. Als Entschuldigung bekommen Sie auch ein Stück Kuchen gratis. Gast: Das ist sehr nett, danke.',
            question: 'Warum wartet der Gast so lange?',
            options: ['a) Das Café ist neu', 'b) Das Café ist voll und hat wenig Personal', 'c) Der Gast hat falsch bestellt'],
            correct: 'b',
          },
        ],
      },
      teil2: {
        instruction: 'Sie hören einen Bericht. Sind die Aussagen richtig oder falsch?',
        replays: 1,
        items: [
          {
            id: 7,
            context: 'Bericht über Sprachlernen',
            audio: 'Laut einer neuen Studie der Universität München ist Musik ein sehr effektives Mittel zum Sprachlernen. Wer Lieder in einer Fremdsprache hört und singt, kann sich neue Vokabeln bis zu dreimal schneller merken als beim normalen Lernen. Besonders Kinder profitieren von dieser Methode. Aber auch für Erwachsene ist es nie zu spät. Die Forscher empfehlen, täglich mindestens zwanzig Minuten Musik in der Zielsprache zu hören. Podcasts und Hörbücher sind ebenfalls hilfreich, aber weniger effektiv als Musik.',
            question: 'Musik hilft beim Sprachlernen.',
            options: ['richtig', 'falsch'],
            correct: 'richtig',
          },
          {
            id: 8,
            context: '',
            audio: '',
            question: 'Kinder können durch Musik doppelt so schnell Vokabeln lernen.',
            options: ['richtig', 'falsch'],
            correct: 'falsch',
          },
          {
            id: 9,
            context: '',
            audio: '',
            question: 'Die Forscher empfehlen täglich zwanzig Minuten Musik zu hören.',
            options: ['richtig', 'falsch'],
            correct: 'richtig',
          },
          {
            id: 10,
            context: '',
            audio: '',
            question: 'Podcasts sind effektiver als Musik beim Sprachlernen.',
            options: ['richtig', 'falsch'],
            correct: 'falsch',
          },
        ],
      },
      teil3: {
        instruction: 'Sie hören ein längeres Gespräch. Zu jedem Punkt gibt es eine Aufgabe.',
        replays: 1,
        items: [
          {
            id: 11,
            context: 'Talkshow über Ernährung',
            audio: 'Moderatorin: Frau Dr. Braun, Sie sind Ernährungsberaterin. Viele Menschen möchten gesünder essen. Was empfehlen Sie? Dr. Braun: Zunächst: Mehr Gemüse und weniger verarbeitete Lebensmittel. Mindestens fünf Portionen Obst und Gemüse täglich. Moderatorin: Und was ist mit Fleisch? Dr. Braun: Fleisch ist nicht verboten, aber wir essen in Deutschland viel zu viel davon. Zweimal pro Woche ist genug. Moderatorin: Viele sagen, gesundes Essen ist teuer. Dr. Braun: Das stimmt nicht unbedingt. Hülsenfrüchte wie Linsen und Bohnen sind sehr günstig und gesund. Saisonales Gemüse kostet auch nicht viel. Das Problem ist oft, dass wir zu viel Fertigessen kaufen, und das ist wirklich teuer. Moderatorin: Was raten Sie für den Alltag? Dr. Braun: Kochen Sie selbst! Auch mit einfachen Rezepten. Und planen Sie Ihre Mahlzeiten im Voraus.',
            question: 'Wie viele Portionen Obst und Gemüse empfiehlt die Ärztin täglich?',
            options: ['a) Drei', 'b) Vier', 'c) Fünf'],
            correct: 'c',
          },
          {
            id: 12,
            context: '',
            audio: '',
            question: 'Wie oft pro Woche sollte man laut Dr. Braun Fleisch essen?',
            options: ['a) Einmal', 'b) Zweimal', 'c) Dreimal'],
            correct: 'b',
          },
          {
            id: 13,
            context: '',
            audio: '',
            question: 'Was sagt Dr. Braun über gesundes Essen und Kosten?',
            options: ['a) Es ist immer teurer', 'b) Es ist nicht unbedingt teurer', 'c) Bioprodukte sind notwendig'],
            correct: 'b',
          },
          {
            id: 14,
            context: '',
            audio: '',
            question: 'Was ist laut Dr. Braun wirklich teuer?',
            options: ['a) Frisches Gemüse', 'b) Fertigessen', 'c) Bio-Fleisch'],
            correct: 'b',
          },
          {
            id: 15,
            context: '',
            audio: '',
            question: 'Was empfiehlt Dr. Braun für den Alltag?',
            options: ['a) Vitaminpräparate nehmen', 'b) Mehr Bio-Produkte kaufen', 'c) Selbst kochen und Mahlzeiten planen'],
            correct: 'c',
          },
        ],
      },
    },
    lesen: {
      teil1: {
        instruction: 'Lesen Sie die fünf Texte. Welche Antwort passt?',
        items: [
          {
            id: 1,
            text: 'VERANSTALTUNGSHINWEIS: Kulturabend im Stadtmuseum — "Kunst trifft Musik"\nFreitag, 14. November, 19:00 Uhr. Eintritt: 8 Euro (ermäßigt: 5 Euro für Schüler und Studenten). Anschließend kleiner Empfang im Foyer. Reservierung empfohlen: 089 / 44 55 66',
            question: 'Wer zahlt weniger Eintritt?',
            options: ['a) Alle Besucher', 'b) Schüler und Studenten', 'c) Rentner und Kinder'],
            correct: 'b',
          },
          {
            id: 2,
            text: 'Lieber Tom, ich habe gehört, dass du nächste Woche Geburtstag hast! Ich kann leider nicht zur Party kommen, weil ich auf Geschäftsreise bin. Aber ich schicke dir morgen ein Geschenk per Post. Ich hoffe, es gefällt dir! Herzliche Glückwünsche im Voraus, deine Tante Sabine',
            question: 'Warum kommt Tante Sabine nicht zur Party?',
            options: ['a) Sie ist krank', 'b) Sie ist auf Geschäftsreise', 'c) Sie hat die Einladung vergessen'],
            correct: 'b',
          },
          {
            id: 3,
            text: 'GASTSTÄTTE ZUM LÖWEN — Neue Speisekarte ab 1. Oktober\nWir freuen uns, Ihnen mitteilen zu dürfen, dass wir ab Oktober unsere Speisekarte um vegetarische und vegane Gerichte erweitern. Die beliebten Klassiker bleiben natürlich auf der Karte. Täglich Mittagsmenü von 11:30 bis 14:00 Uhr. Reservierungen: 0711 / 33 22 11',
            question: 'Was ist neu bei der Gaststätte?',
            options: ['a) Neue Öffnungszeiten', 'b) Vegetarische und vegane Gerichte', 'c) Ein neuer Koch'],
            correct: 'b',
          },
          {
            id: 4,
            text: 'Nachricht an alle Studierenden: Die Klausuranmeldung für das Wintersemester ist ab sofort bis zum 30. November möglich. Bitte melden Sie sich rechtzeitig im Online-Portal an. Wer sich nicht anmeldet, kann nicht an der Prüfung teilnehmen. Bei Fragen wenden Sie sich an das Prüfungsamt.',
            question: 'Was müssen Studierende bis zum 30. November tun?',
            options: ['a) Die Semestergebühren bezahlen', 'b) Sich für Klausuren anmelden', 'c) Ihre Noten überprüfen'],
            correct: 'b',
          },
          {
            id: 5,
            text: 'WOHNGEMEINSCHAFT SUCHT MITBEWOHNER/IN\n3-er WG in Schwabing sucht eine ruhige Person ab Februar. 18 m² Zimmer. Gemeinschaftsküche und Bad. Gesamtkosten: 620 € warm. Keine Haustiere, kein Rauchen in der Wohnung. Melde dich bei: wg.schwabing@gmail.com',
            question: 'Was ist in den 620 Euro enthalten?',
            options: ['a) Nur die Kaltmiete', 'b) Alles inklusive (warm)', 'c) Miete plus Strom'],
            correct: 'b',
          },
        ],
      },
      teil2: {
        instruction: 'Lesen Sie den Text. Richtig oder falsch?',
        items: [
          {
            id: 6,
            text: 'ERFAHRUNGSBERICHT: Mein erster Marathon\nVor einem Jahr hätte ich nie gedacht, dass ich einen Marathon laufen würde. Ich war kein sportlicher Mensch — nach der Schule hatte ich kaum noch Sport gemacht. Dann hat mir meine Freundin Petra vorgeschlagen, gemeinsam für einen Halbmarathon zu trainieren. Am Anfang konnte ich kaum fünf Kilometer am Stück laufen. Aber nach sechs Monaten Training war ich bereit. Beim Halbmarathon habe ich so viel Spaß gehabt, dass ich gleich für den vollen Marathon angemeldet habe. Nach einem weiteren Jahr intensivem Training habe ich ihn in vier Stunden und zwölf Minuten geschafft. Das war das Stolzeste in meinem Leben!',
            question: 'Vor dem Training war die Person sehr sportlich.',
            options: ['richtig', 'falsch'],
            correct: 'falsch',
          },
          {
            id: 7,
            text: '',
            question: 'Eine Freundin hat die Person zum Sport motiviert.',
            options: ['richtig', 'falsch'],
            correct: 'richtig',
          },
          {
            id: 8,
            text: '',
            question: 'Das Training für den Halbmarathon dauerte sechs Monate.',
            options: ['richtig', 'falsch'],
            correct: 'richtig',
          },
          {
            id: 9,
            text: '',
            question: 'Nach dem Halbmarathon hat sich die Person direkt für den Marathon angemeldet.',
            options: ['richtig', 'falsch'],
            correct: 'richtig',
          },
          {
            id: 10,
            text: '',
            question: 'Die Person hat den Marathon in weniger als vier Stunden geschafft.',
            options: ['richtig', 'falsch'],
            correct: 'falsch',
          },
        ],
      },
      teil3: {
        instruction: 'Lesen Sie den Text und die Aufgaben.',
        items: [
          {
            id: 11,
            text: 'WAS BEDEUTET INTEGRATION?\nIntegration bedeutet nicht, die eigene Kultur aufzugeben. Es geht darum, in einer neuen Gesellschaft anzukommen und gleichzeitig die eigene Identität zu bewahren. Sprachkenntnisse sind der erste und wichtigste Schritt. Ohne die Landessprache ist es fast unmöglich, wirklich Teil der Gesellschaft zu werden. Aber Sprache allein reicht nicht. Soziale Kontakte zu Menschen aus dem Gastland sind genauso wichtig. Vereine, Sportclubs oder Nachbarschaftsinitiativen bieten gute Möglichkeiten. Arbeit spielt ebenfalls eine zentrale Rolle: Ein Job gibt nicht nur Einkommen, sondern auch Struktur und soziale Kontakte. Studien zeigen, dass Menschen, die schnell Arbeit finden, sich auch schneller in der neuen Heimat wohlfühlen.',
            question: 'Was ist laut dem Text der erste Schritt zur Integration?',
            options: ['a) Einen Job finden', 'b) Die Sprache lernen', 'c) Freunde finden'],
            correct: 'b',
          },
          {
            id: 12,
            text: '',
            question: 'Was ist neben der Sprache noch wichtig?',
            options: ['a) Die eigene Kultur aufgeben', 'b) Soziale Kontakte zu Menschen aus dem Gastland', 'c) Viel Geld verdienen'],
            correct: 'b',
          },
          {
            id: 13,
            text: '',
            question: 'Welche Orte werden als Möglichkeit für Kontakte genannt?',
            options: ['a) Schulen und Universitäten', 'b) Einkaufszentren', 'c) Vereine und Sportclubs'],
            correct: 'c',
          },
          {
            id: 14,
            text: '',
            question: 'Was gibt Arbeit außer Einkommen noch?',
            options: ['a) Staatliche Unterstützung', 'b) Struktur und soziale Kontakte', 'c) Kostenlose Sprachkurse'],
            correct: 'b',
          },
          {
            id: 15,
            text: '',
            question: 'Was zeigen Studien über Menschen, die schnell Arbeit finden?',
            options: ['a) Sie verdienen mehr Geld', 'b) Sie fühlen sich schneller wohl', 'c) Sie lernen die Sprache schneller'],
            correct: 'b',
          },
        ],
      },
    },
    schreiben: {
      teil1: {
        instruction: 'Lesen Sie die Informationen. Füllen Sie das Anmeldeformular aus.',
        formTitle: 'Anmeldung — Deutschkurs B1',
        personCard: [
          'Name: Amina Yilmaz',
          'Geburtsdatum: 22.06.1988',
          'Herkunftsland: Türkei',
          'Adresse: Beethovenstraße 14, 10115 Berlin',
          'Telefon: 030 / 55 44 33',
          'Aktuelles Sprachniveau: A2 (Zertifikat vom 15.03.2023)',
          'Gewünschter Kurs: B1 Intensivkurs (Montag – Freitag)',
          'Bemerkung: Möchte gerne morgens lernen',
        ],
        fields: [
          { label: 'Name und Vorname', answer: 'Yilmaz Amina', hint: 'Nachname zuerst' },
          { label: 'Geburtsdatum', answer: '22.06.1988' },
          { label: 'Herkunftsland', answer: 'Türkei' },
          { label: 'Aktuelles Sprachniveau', answer: 'A2' },
          { label: 'Gewünschter Kurs', answer: 'B1 Intensivkurs' },
        ],
      },
      teil2: {
        instruction: 'Schreiben Sie eine kurze Nachricht an Ihre Hausverwaltung.',
        situation: 'In Ihrer Wohnung gibt es seit drei Tagen ein Problem mit der Heizung. Es ist sehr kalt. Sie haben die Hausverwaltung zweimal angerufen, aber niemand hat zurückgerufen.',
        bullets: [
          'Beschreiben Sie das Problem mit der Heizung',
          'Erklären Sie, seit wann das Problem besteht',
          'Erwähnen Sie, dass Sie schon zweimal angerufen haben',
          'Bitten Sie um schnelle Hilfe',
        ],
        minWords: 50,
      },
    },
    sprechen: {
      teil1: {
        teil: 1,
        instruction: 'Berichten Sie über ein wichtiges Erlebnis aus Ihrem Leben.',
        prompts: [
          'Beschreiben Sie ein unvergessliches Erlebnis',
          'Wann und wo war das?',
          'Was haben Sie gefühlt?',
          'Was haben Sie daraus gelernt?',
        ],
        exampleResponse: 'Ein wichtiges Erlebnis war... Das war vor... Jahren in... Ich habe damals... gefühlt. Es hat mich gelehrt, dass...',
      },
      teil2: {
        teil: 2,
        instruction: 'Sie und ein Freund möchten ein Geschenk für einen gemeinsamen Freund kaufen.',
        prompts: [
          'Machen Sie einen Vorschlag für ein Geschenk',
          'Sprechen Sie über das Budget',
          'Einigen Sie sich auf eine Idee',
          'Besprechen Sie, wer das Geschenk kauft',
        ],
      },
      teil3: {
        teil: 3,
        instruction: 'Sprechen Sie über Technologie in Ihrem Alltag.',
        prompts: [
          'Welche Geräte benutzen Sie täglich?',
          'Was können Sie ohne Smartphone nicht machen?',
          'Was sind die Vorteile und Nachteile von Social Media?',
          'Wie war das Leben vor dem Internet?',
        ],
      },
    },
  },
];
