// A2 Grammar Game Data
import type { FillInQuestion, SentenceExercise } from './grammar-games-data';

export const fillInQuestionsA2: FillInQuestion[] = [
  // ── Perfekt ───────────────────────────────────────────────────
  {
    sentence: 'Ich ___ gestern viel gearbeitet.',
    options: ['habe', 'bin', 'hatte', 'war'],
    correct: 'habe',
    category: 'conjugation',
    explanation: 'arbeiten → Perfekt mit haben: ich habe gearbeitet',
    explanationEn: 'arbeiten takes "haben" in the Perfekt: ich habe gearbeitet',
  },
  {
    sentence: 'Wir ___ letzten Sommer nach Spanien gefahren.',
    options: ['sind', 'haben', 'waren', 'hatten'],
    correct: 'sind',
    category: 'conjugation',
    explanation: 'fahren → Perfekt mit sein: wir sind gefahren',
    explanationEn: 'fahren (movement verb) takes "sein" in the Perfekt',
  },
  {
    sentence: 'Er ___ schon gegessen.',
    options: ['hat', 'ist', 'hatte', 'war'],
    correct: 'hat',
    category: 'conjugation',
    explanation: 'essen → Perfekt mit haben: er hat gegessen',
    explanationEn: 'essen takes "haben" in the Perfekt',
  },
  {
    sentence: 'Sie ___ um 8 Uhr aufgestanden.',
    options: ['ist', 'hat', 'war', 'hatte'],
    correct: 'ist',
    category: 'conjugation',
    explanation: 'aufstehen → Zustandswechsel → Perfekt mit sein',
    explanationEn: 'aufstehen (change of state) takes "sein" in the Perfekt',
  },
  {
    sentence: 'Hast du den Film ___?',
    options: ['gesehen', 'sehen', 'siehst', 'sahst'],
    correct: 'gesehen',
    category: 'conjugation',
    explanation: 'sehen → Partizip II: gesehen',
    explanationEn: 'sehen → past participle: gesehen (irregular)',
  },
  {
    sentence: 'Ich habe ihm einen Brief ___.',
    options: ['geschrieben', 'schreiben', 'schrieb', 'schreibt'],
    correct: 'geschrieben',
    category: 'conjugation',
    explanation: 'schreiben → Partizip II: geschrieben',
    explanationEn: 'schreiben → past participle: geschrieben (irregular)',
  },
  // ── Dativ ─────────────────────────────────────────────────────
  {
    sentence: 'Ich gebe ___ Kind das Buch.',
    options: ['dem', 'den', 'der', 'das'],
    correct: 'dem',
    category: 'accusative',
    explanation: 'das Kind → Dativ: dem Kind (Hilfsverb nehmen = Objekt)',
    explanationEn: 'das Kind → dative: dem Kind (neutral in dative)',
  },
  {
    sentence: 'Er hilft ___ alten Frau.',
    options: ['der', 'die', 'den', 'dem'],
    correct: 'der',
    category: 'accusative',
    explanation: 'die Frau → Dativ: der Frau (feminin Dativ)',
    explanationEn: 'die Frau → dative: der Frau (feminine dative)',
  },
  {
    sentence: 'Ich fahre ___ dem Bus.',
    options: ['mit', 'von', 'zu', 'bei'],
    correct: 'mit',
    category: 'accusative',
    explanation: 'mit + Dativ: mit dem Bus (Transportmittel)',
    explanationEn: 'mit + dative is used for means of transport',
  },
  {
    sentence: 'Seit ___ Jahr lerne ich Deutsch.',
    options: ['einem', 'ein', 'eine', 'einer'],
    correct: 'einem',
    category: 'accusative',
    explanation: 'seit + Dativ: seit einem Jahr (neutral Dativ)',
    explanationEn: 'seit + dative: einem Jahr (neutral dative)',
  },
  // ── Konjunktionen ─────────────────────────────────────────────
  {
    sentence: 'Ich lerne Deutsch, ___ ich in Deutschland arbeiten möchte.',
    options: ['weil', 'dass', 'wenn', 'obwohl'],
    correct: 'weil',
    category: 'conjugation',
    explanation: 'weil = because (Begründung), Verb ans Ende',
    explanationEn: 'weil = because (giving a reason), verb goes to the end',
  },
  {
    sentence: 'Er sagt, ___ er morgen kommt.',
    options: ['dass', 'weil', 'wenn', 'obwohl'],
    correct: 'dass',
    category: 'conjugation',
    explanation: 'dass leitet einen Nebensatz ein (indirekte Rede)',
    explanationEn: 'dass introduces a subordinate clause (reported speech)',
  },
  {
    sentence: '___ es regnet, nehme ich einen Regenschirm.',
    options: ['Wenn', 'Dass', 'Weil', 'Obwohl'],
    correct: 'Wenn',
    category: 'conjugation',
    explanation: 'wenn = when/if (Bedingung)',
    explanationEn: 'wenn = when/if (condition)',
  },
  {
    sentence: '___ es kalt war, sind wir schwimmen gegangen.',
    options: ['Obwohl', 'Weil', 'Dass', 'Wenn'],
    correct: 'Obwohl',
    category: 'conjugation',
    explanation: 'obwohl = although (Einschränkung)',
    explanationEn: 'obwohl = although (contradiction)',
  },
  // ── Komparativ ───────────────────────────────────────────────
  {
    sentence: 'München ist ___ als Nürnberg.',
    options: ['größer', 'groß', 'am größten', 'größte'],
    correct: 'größer',
    category: 'conjugation',
    explanation: 'Komparativ: groß → größer (+ als für Vergleich)',
    explanationEn: 'Comparative: groß → größer (+ als for comparison)',
  },
  {
    sentence: 'Das ist das ___ Restaurant in der Stadt.',
    options: ['beste', 'besser', 'gut', 'am besten'],
    correct: 'beste',
    category: 'conjugation',
    explanation: 'Superlativ attributiv: das beste Restaurant',
    explanationEn: 'Attributive superlative: das beste (before the noun)',
  },
  {
    sentence: 'Er läuft ___ als sein Bruder.',
    options: ['schneller', 'schnell', 'am schnellsten', 'schnellste'],
    correct: 'schneller',
    category: 'conjugation',
    explanation: 'Komparativ: schnell → schneller + als',
    explanationEn: 'Comparative: schnell → schneller + als',
  },
  // ── Reflexive Verben ──────────────────────────────────────────
  {
    sentence: 'Ich freue ___ auf den Urlaub.',
    options: ['mich', 'mir', 'sich', 'dich'],
    correct: 'mich',
    category: 'conjugation',
    explanation: 'sich freuen: ich → mich (Akkusativ Reflexivpronomen)',
    explanationEn: 'sich freuen: ich → mich (accusative reflexive pronoun)',
  },
  {
    sentence: 'Er zieht ___ schnell an.',
    options: ['sich', 'ihm', 'ihn', 'mich'],
    correct: 'sich',
    category: 'conjugation',
    explanation: 'sich anziehen: er/sie/es → sich',
    explanationEn: 'sich anziehen (to get dressed): er/sie/es → sich',
  },
  {
    sentence: 'Wir treffen ___ um 19 Uhr.',
    options: ['uns', 'sich', 'euch', 'mich'],
    correct: 'uns',
    category: 'conjugation',
    explanation: 'sich treffen: wir → uns',
    explanationEn: 'sich treffen (to meet): wir → uns',
  },
  // ── Präteritum ───────────────────────────────────────────────
  {
    sentence: 'Als Kind ___ sie sehr sportlich.',
    options: ['war', 'ist', 'hatte', 'hat'],
    correct: 'war',
    category: 'conjugation',
    explanation: 'sein Präteritum: sie war (in Vergangenheitsbeschreibungen)',
    explanationEn: 'sein simple past: sie war (for past descriptions)',
  },
  {
    sentence: 'Er ___ keine Zeit.',
    options: ['hatte', 'hat', 'war', 'ist'],
    correct: 'hatte',
    category: 'conjugation',
    explanation: 'haben Präteritum: er hatte',
    explanationEn: 'haben simple past: er hatte',
  },
  {
    sentence: 'Wir ___ nicht kommen.',
    options: ['konnten', 'können', 'könnten', 'konntest'],
    correct: 'konnten',
    category: 'modal',
    explanation: 'können Präteritum: wir konnten',
    explanationEn: 'können simple past: wir konnten (we were not able to)',
  },
  {
    sentence: 'Sie ___ früh aufstehen.',
    options: ['musste', 'muss', 'müsste', 'musstet'],
    correct: 'musste',
    category: 'modal',
    explanation: 'müssen Präteritum: sie musste',
    explanationEn: 'müssen simple past: sie musste (she had to)',
  },
  // ── Negation / Dativ Präpositionen ───────────────────────────
  {
    sentence: '___ des Regens blieben wir zu Hause.',
    options: ['Wegen', 'Obwohl', 'Damit', 'Während'],
    correct: 'Wegen',
    category: 'negation',
    explanation: 'wegen + Genitiv (Ursache)',
    explanationEn: 'wegen + genitive (because of / due to)',
  },
  {
    sentence: '___ des schlechten Wetters gingen wir trotzdem raus.',
    options: ['Trotz', 'Wegen', 'Während', 'Statt'],
    correct: 'Trotz',
    category: 'negation',
    explanation: 'trotz + Genitiv (Einschränkung)',
    explanationEn: 'trotz + genitive (despite / in spite of)',
  },
];

export const sentenceExercisesA2: SentenceExercise[] = [
  {
    words: ['Ich', 'habe', 'gestern', 'einen', 'Film', 'gesehen'],
    focus: 'Perfekt',
    tip: 'Perfekt: haben/sein an Position 2, Partizip II ans Ende.',
    tipEn: 'Perfekt: haben/sein at position 2, past participle at the end.',
  },
  {
    words: ['Wir', 'sind', 'letztes', 'Jahr', 'nach', 'Paris', 'gefahren'],
    focus: 'Perfekt mit sein',
    tip: 'Bewegungsverben nehmen sein: sind...gefahren.',
    tipEn: 'Movement verbs take "sein": sind...gefahren.',
  },
  {
    words: ['Ich', 'lerne', 'Deutsch,', 'weil', 'ich', 'hier', 'arbeiten', 'will'],
    focus: 'Nebensatz mit weil',
    tip: 'Nach "weil" steht das Verb am Ende des Nebensatzes.',
    tipEn: 'After "weil", the verb goes to the END of the clause.',
  },
  {
    words: ['Er', 'sagt,', 'dass', 'er', 'morgen', 'nicht', 'kommen', 'kann'],
    focus: 'Nebensatz mit dass',
    tip: 'Nach "dass" steht das Verb am Satzende (auch Modalverb).',
    tipEn: 'After "dass", the verb goes to the end (even modal verbs).',
  },
  {
    words: ['Obwohl', 'es', 'regnete,', 'gingen', 'wir', 'spazieren'],
    focus: 'Nebensatz mit obwohl + V2',
    tip: 'Obwohl-Nebensatz → Verb am Ende. Hauptsatz danach: Verb an Position 1.',
    tipEn: 'obwohl-clause → verb at end. Main clause after: verb at position 1.',
  },
  {
    words: ['München', 'ist', 'größer', 'als', 'Nürnberg'],
    focus: 'Komparativ',
    tip: 'Vergleich: Komparativ + als.',
    tipEn: 'Comparison: comparative + als.',
  },
  {
    words: ['Ich', 'freue', 'mich', 'auf', 'den', 'Urlaub'],
    focus: 'Reflexivverb',
    tip: 'sich freuen: ich freue MICH (Reflexivpronomen nach dem Verb).',
    tipEn: 'sich freuen: ich freue MICH (reflexive pronoun after the verb).',
  },
  {
    words: ['Das', 'war', 'das', 'beste', 'Essen', 'meines', 'Lebens'],
    focus: 'Superlativ + Genitiv',
    tip: 'Attributiver Superlativ: das beste. Genitiv: meines Lebens.',
    tipEn: 'Attributive superlative: das beste. Genitive: meines Lebens.',
  },
  {
    words: ['Sie', 'musste', 'früh', 'aufstehen,', 'weil', 'der', 'Zug', 'früh', 'abfuhr'],
    focus: 'Präteritum + weil',
    tip: 'Präteritum: musste, abfuhr. Weil-Nebensatz: Verb ans Ende.',
    tipEn: 'Simple past: musste, abfuhr. weil-clause: verb to the end.',
  },
  {
    words: ['Wegen', 'des', 'Staus', 'kamen', 'wir', 'zu', 'spät', 'an'],
    focus: 'Genitiv mit wegen + V2',
    tip: 'wegen + Genitiv. Dann: Verb-Subjekt Inversion (V2 nach Adverbial).',
    tipEn: 'wegen + genitive. Then: verb-subject inversion (V2 after adverbial).',
  },
];
