// B1 Grammar Game Data
import type { FillInQuestion, SentenceExercise } from './grammar-games-data';

export const fillInQuestionsB1: FillInQuestion[] = [
  // ── Konjunktiv II ─────────────────────────────────────────────
  {
    sentence: 'Ich ___ gerne nach Japan reisen.',
    options: ['würde', 'werde', 'bin', 'wäre'],
    correct: 'würde',
    category: 'modal',
    explanation: 'Konjunktiv II: würde + Infinitiv (Wunsch)',
    explanationEn: 'Subjunctive II: würde + infinitive (expressing a wish)',
  },
  {
    sentence: 'Wenn ich reich ___, würde ich die Welt bereisen.',
    options: ['wäre', 'bin', 'war', 'würde'],
    correct: 'wäre',
    category: 'conjugation',
    explanation: 'Konjunktiv II von sein: wäre (hypothetische Bedingung)',
    explanationEn: 'Subjunctive II of sein: wäre (hypothetical condition)',
  },
  {
    sentence: '___ du mir bitte helfen?',
    options: ['Könntest', 'Kannst', 'Konntest', 'Könntet'],
    correct: 'Könntest',
    category: 'modal',
    explanation: 'Konjunktiv II von können: könntest (höfliche Bitte)',
    explanationEn: 'Subjunctive II of können: könntest (polite request)',
  },
  {
    sentence: 'Er ___ mehr Sport machen.',
    options: ['sollte', 'soll', 'solltest', 'sollten'],
    correct: 'sollte',
    category: 'modal',
    explanation: 'Konjunktiv II von sollen: sollte (Empfehlung)',
    explanationEn: 'Subjunctive II of sollen: sollte (recommendation)',
  },
  {
    sentence: 'Ich ___ gerne einen Kaffee.',
    options: ['hätte', 'habe', 'hatte', 'wäre'],
    correct: 'hätte',
    category: 'modal',
    explanation: 'Konjunktiv II von haben: hätte (höfliche Bestellung)',
    explanationEn: 'Subjunctive II of haben: hätte (polite request in a café/restaurant)',
  },
  // ── Passiv ────────────────────────────────────────────────────
  {
    sentence: 'Das Buch ___ von Goethe geschrieben.',
    options: ['wurde', 'hat', 'war', 'ist'],
    correct: 'wurde',
    category: 'conjugation',
    explanation: 'Passiv Präteritum: wurde + Partizip II',
    explanationEn: 'Passive in simple past: wurde + past participle',
  },
  {
    sentence: 'Die Tür ___ um 20 Uhr geschlossen.',
    options: ['wird', 'ist', 'hat', 'wurde'],
    correct: 'wird',
    category: 'conjugation',
    explanation: 'Passiv Präsens: wird + Partizip II',
    explanationEn: 'Passive in present tense: wird + past participle',
  },
  {
    sentence: 'Der Brief ___ bereits abgeschickt worden.',
    options: ['ist', 'hat', 'war', 'wird'],
    correct: 'ist',
    category: 'conjugation',
    explanation: 'Passiv Perfekt: ist + Partizip II + worden',
    explanationEn: 'Passive in perfect tense: ist + past participle + worden',
  },
  {
    sentence: 'Das Fenster ___ von den Kindern zerbrochen.',
    options: ['wurde', 'hat', 'ist', 'wird'],
    correct: 'wurde',
    category: 'conjugation',
    explanation: 'Passiv Präteritum mit von + Dativ',
    explanationEn: 'Passive simple past with von + dative (agent)',
  },
  // ── Relativsätze ──────────────────────────────────────────────
  {
    sentence: 'Das ist der Mann, ___ mir geholfen hat.',
    options: ['der', 'den', 'dem', 'dessen'],
    correct: 'der',
    category: 'conjugation',
    explanation: 'Relativpronomen: Nominativ maskulin → der',
    explanationEn: 'Relative pronoun: nominative masculine → der (subject of the clause)',
  },
  {
    sentence: 'Das Buch, ___ ich lese, ist spannend.',
    options: ['das', 'den', 'dem', 'der'],
    correct: 'das',
    category: 'conjugation',
    explanation: 'Relativpronomen: Akkusativ neutral → das',
    explanationEn: 'Relative pronoun: accusative neuter → das',
  },
  {
    sentence: 'Das ist die Frau, ___ Auto gestohlen wurde.',
    options: ['deren', 'die', 'der', 'denen'],
    correct: 'deren',
    category: 'conjugation',
    explanation: 'Relativpronomen Genitiv feminin → deren',
    explanationEn: 'Relative pronoun genitive feminine → deren (whose)',
  },
  {
    sentence: 'Die Leute, ___ ich spreche, sind nett.',
    options: ['mit denen', 'mit die', 'mit der', 'mit den'],
    correct: 'mit denen',
    category: 'conjugation',
    explanation: 'Präposition + Relativpronomen Dativ Plural: mit denen',
    explanationEn: 'Preposition + relative pronoun dative plural: mit denen',
  },
  // ── Wechselpräpositionen ──────────────────────────────────────
  {
    sentence: 'Das Bild hängt ___ der Wand.',
    options: ['an', 'auf', 'in', 'über'],
    correct: 'an',
    category: 'accusative',
    explanation: 'hängen (Lage) → an + Dativ: an der Wand',
    explanationEn: 'hängen (location) → an + dative: an der Wand',
  },
  {
    sentence: 'Ich hänge das Bild ___ die Wand.',
    options: ['an', 'an der', 'auf die', 'in die'],
    correct: 'an',
    category: 'accusative',
    explanation: 'hängen (Bewegung) → an + Akkusativ: an die Wand',
    explanationEn: 'hängen (movement) → an + accusative: an die Wand',
  },
  {
    sentence: 'Das Buch liegt ___ dem Tisch.',
    options: ['auf', 'an', 'in', 'über'],
    correct: 'auf',
    category: 'accusative',
    explanation: 'liegen (Lage) → auf + Dativ: auf dem Tisch',
    explanationEn: 'liegen (location) → auf + dative: auf dem Tisch',
  },
  {
    sentence: 'Sie legt das Buch ___ den Tisch.',
    options: ['auf', 'auf dem', 'an den', 'in den'],
    correct: 'auf',
    category: 'accusative',
    explanation: 'legen (Bewegung) → auf + Akkusativ: auf den Tisch',
    explanationEn: 'legen (movement) → auf + accusative: auf den Tisch',
  },
  // ── Genitiv ───────────────────────────────────────────────────
  {
    sentence: 'Am Ende ___ Films gibt es eine Überraschung.',
    options: ['des', 'dem', 'den', 'der'],
    correct: 'des',
    category: 'accusative',
    explanation: 'Genitiv neutral: am Ende des Films',
    explanationEn: 'Genitive neuter: des Films (the ending of -s)',
  },
  {
    sentence: 'Die Hauptstadt ___ ist Berlin.',
    options: ['Deutschlands', 'Deutschland', 'dem Deutschland', 'des Deutschlands'],
    correct: 'Deutschlands',
    category: 'accusative',
    explanation: 'Eigennamen im Genitiv: + s (ohne Artikel)',
    explanationEn: 'Proper nouns in genitive: + s (no article)',
  },
  {
    sentence: '___ des schlechten Wetters gingen wir trotzdem raus.',
    options: ['Trotz', 'Wegen', 'Während', 'Statt'],
    correct: 'Trotz',
    category: 'negation',
    explanation: 'trotz + Genitiv: trotz des Wetters',
    explanationEn: 'trotz + genitive: despite the weather',
  },
  // ── Indirekte Rede ────────────────────────────────────────────
  {
    sentence: 'Der Arzt sagt, ___ ich mehr schlafen soll.',
    options: ['dass', 'weil', 'wenn', 'obwohl'],
    correct: 'dass',
    category: 'conjugation',
    explanation: 'Indirekte Rede: sagen + dass + Nebensatz (Verb ans Ende)',
    explanationEn: 'Reported speech: sagen + dass + subordinate clause (verb to end)',
  },
  {
    sentence: 'Sie berichtet, dass der Zug Verspätung ___.',
    options: ['hat', 'hatte', 'haben', 'hätte'],
    correct: 'hat',
    category: 'conjugation',
    explanation: 'In indirekter Rede mit dass: Indikativ Präsens',
    explanationEn: 'In reported speech with dass: indicative present',
  },
  // ── Konjunktiv II — Ratschläge ────────────────────────────────
  {
    sentence: 'Du ___ mehr Gemüse essen.',
    options: ['solltest', 'sollst', 'should', 'musst'],
    correct: 'solltest',
    category: 'modal',
    explanation: 'Ratschlag: du solltest + Infinitiv',
    explanationEn: 'Advice/recommendation: du solltest + infinitive',
  },
  {
    sentence: 'An deiner Stelle ___ ich das nicht machen.',
    options: ['würde', 'werde', 'würdest', 'bin'],
    correct: 'würde',
    category: 'modal',
    explanation: 'An deiner Stelle würde ich... (Ratschlag)',
    explanationEn: '"If I were you, I would..." — giving advice',
  },
];

export const sentenceExercisesB1: SentenceExercise[] = [
  {
    words: ['Wenn', 'ich', 'Zeit', 'hätte,', 'würde', 'ich', 'reisen'],
    focus: 'Konjunktiv II — Hypothese',
    tip: 'Bedingungssatz (wenn + Konj. II) → Hauptsatz (würde + Infinitiv).',
    tipEn: 'Conditional clause (wenn + subj. II) → main clause (würde + infinitive).',
  },
  {
    words: ['Das', 'Buch', 'wurde', 'von', 'Goethe', 'geschrieben'],
    focus: 'Passiv Präteritum',
    tip: 'Passiv Vergangenheit: wurde + Partizip II. Handelnder: von + Dativ.',
    tipEn: 'Passive past: wurde + past participle. Agent: von + dative.',
  },
  {
    words: ['Die', 'Tür', 'wird', 'jeden', 'Abend', 'um', '22', 'Uhr', 'geschlossen'],
    focus: 'Passiv Präsens',
    tip: 'Passiv Gegenwart: wird + Partizip II.',
    tipEn: 'Passive present: wird + past participle.',
  },
  {
    words: ['Das', 'ist', 'der', 'Mann,', 'der', 'mir', 'geholfen', 'hat'],
    focus: 'Relativsatz — Nominativ',
    tip: 'Relativpronomen richtet sich nach Genus des Bezugsnomens: der Mann → der.',
    tipEn: 'Relative pronoun agrees with the noun: der Mann → der.',
  },
  {
    words: ['Das', 'Buch,', 'das', 'ich', 'lese,', 'ist', 'sehr', 'interessant'],
    focus: 'Relativsatz — Akkusativ neutral',
    tip: 'das Buch, Akkusativ → das. Verb im Relativsatz ans Ende.',
    tipEn: 'das Buch, accusative neutral → das. Verb to the end.',
  },
  {
    words: ['Das', 'Bild', 'hängt', 'an', 'der', 'Wand'],
    focus: 'Wechselpräposition — Dativ (Lage)',
    tip: 'Lage: an + Dativ → an der Wand. Frage: Wo hängt es?',
    tipEn: 'Location: an + dative → an der Wand. Question: Where is it?',
  },
  {
    words: ['Ich', 'hänge', 'das', 'Bild', 'an', 'die', 'Wand'],
    focus: 'Wechselpräposition — Akkusativ (Bewegung)',
    tip: 'Bewegung: an + Akkusativ → an die Wand. Frage: Wohin?',
    tipEn: 'Movement: an + accusative → an die Wand. Question: Where to?',
  },
  {
    words: ['Trotz', 'des', 'Regens', 'gingen', 'wir', 'spazieren'],
    focus: 'Genitiv mit trotz + V2',
    tip: 'trotz + Genitiv. Danach V2-Inversion: Verb vor Subjekt.',
    tipEn: 'trotz + genitive. Then V2 inversion: verb before subject.',
  },
  {
    words: ['Er', 'sagt,', 'dass', 'er', 'morgen', 'nicht', 'kommen', 'kann'],
    focus: 'Indirekte Rede + Modalverb',
    tip: 'Indirekte Rede: dass + Subjekt... Verb ans Ende (auch Modalverb).',
    tipEn: 'Reported speech: dass + subject... verb to the end (incl. modal).',
  },
  {
    words: ['An', 'deiner', 'Stelle', 'würde', 'ich', 'das', 'nicht', 'machen'],
    focus: 'Konjunktiv II — Ratschlag',
    tip: 'An deiner Stelle würde ich... = If I were you, I would...',
    tipEn: '"An deiner Stelle würde ich..." = "If I were you, I would..."',
  },
];
