// A2 Level Study Data — Vocabulary & Grammar

import type { VocabTopic, GrammarRule } from './study-data';

export const vocabularyA2: VocabTopic[] = [
  {
    id: 'a2-work',
    name: 'Arbeit & Beruf',
    nameEn: 'Work & Career',
    icon: 'briefcase',
    level: 'A2',
    words: [
      { german: 'Bewerbung', article: 'die', plural: 'Bewerbungen', english: 'job application', example: 'Ich schicke eine Bewerbung.' },
      { german: 'Lebenslauf', article: 'der', plural: 'Lebensläufe', english: 'CV / résumé', example: 'Mein Lebenslauf ist aktuell.' },
      { german: 'Vorstellungsgespräch', article: 'das', plural: 'Vorstellungsgespräche', english: 'job interview', example: 'Das Vorstellungsgespräch war schwierig.' },
      { german: 'Stelle', article: 'die', plural: 'Stellen', english: 'position / job', example: 'Ich suche eine neue Stelle.' },
      { german: 'Kollege', article: 'der', plural: 'Kollegen', english: 'colleague (m.)', example: 'Mein Kollege ist sehr nett.' },
      { german: 'Kollegin', article: 'die', plural: 'Kolleginnen', english: 'colleague (f.)', example: 'Meine Kollegin kommt aus Österreich.' },
      { german: 'Chef', article: 'der', plural: 'Chefs', english: 'boss (m.)', example: 'Mein Chef ist streng aber fair.' },
      { german: 'Gehalt', article: 'das', plural: 'Gehälter', english: 'salary', example: 'Das Gehalt ist gut.' },
      { german: 'Urlaub', article: 'der', plural: 'Urlaube', english: 'holiday / vacation', example: 'Ich habe drei Wochen Urlaub.' },
      { german: 'kündigen', english: 'to resign / quit', example: 'Er hat gekündigt.' },
      { german: 'eingestellt werden', english: 'to be hired', example: 'Sie wurde eingestellt.' },
      { german: 'Überstunden', article: 'die', english: 'overtime', example: 'Ich mache oft Überstunden.' },
      { german: 'Teilzeit', article: 'die', english: 'part-time', example: 'Sie arbeitet in Teilzeit.' },
      { german: 'Vollzeit', article: 'die', english: 'full-time', example: 'Er arbeitet Vollzeit.' },
      { german: 'Praktikum', article: 'das', plural: 'Praktika', english: 'internship', example: 'Ich mache ein Praktikum.' },
      { german: 'Besprechung', article: 'die', plural: 'Besprechungen', english: 'meeting', example: 'Die Besprechung dauert zwei Stunden.' },
      { german: 'Abteilung', article: 'die', plural: 'Abteilungen', english: 'department', example: 'Ich arbeite in der Marketingabteilung.' },
      { german: 'Vertrag', article: 'der', plural: 'Verträge', english: 'contract', example: 'Ich habe einen unbefristeten Vertrag.' },
      { german: 'Rente', article: 'die', english: 'pension / retirement', example: 'Er geht nächstes Jahr in Rente.' },
      { german: 'selbstständig', english: 'self-employed', example: 'Sie ist selbstständig als Ärztin.' },
    ],
  },
  {
    id: 'a2-health',
    name: 'Gesundheit & Körper',
    nameEn: 'Health & Body',
    icon: 'heart',
    level: 'A2',
    words: [
      { german: 'Schmerzen', article: 'die', english: 'pain', example: 'Ich habe Schmerzen im Rücken.' },
      { german: 'Fieber', article: 'das', english: 'fever', example: 'Das Kind hat hohes Fieber.' },
      { german: 'Erkältung', article: 'die', plural: 'Erkältungen', english: 'cold (illness)', example: 'Ich habe eine Erkältung.' },
      { german: 'Grippe', article: 'die', english: 'flu', example: 'Er liegt mit Grippe im Bett.' },
      { german: 'Arzt', article: 'der', plural: 'Ärzte', english: 'doctor (m.)', example: 'Ich gehe zum Arzt.' },
      { german: 'Ärztin', article: 'die', plural: 'Ärztinnen', english: 'doctor (f.)', example: 'Die Ärztin ist sehr freundlich.' },
      { german: 'Rezept', article: 'das', plural: 'Rezepte', english: 'prescription / recipe', example: 'Der Arzt gibt mir ein Rezept.' },
      { german: 'Medikament', article: 'das', plural: 'Medikamente', english: 'medication', example: 'Nehmen Sie das Medikament dreimal täglich.' },
      { german: 'Termin', article: 'der', plural: 'Termine', english: 'appointment', example: 'Ich habe einen Termin beim Arzt.' },
      { german: 'Krankenhaus', article: 'das', plural: 'Krankenhäuser', english: 'hospital', example: 'Er war eine Woche im Krankenhaus.' },
      { german: 'Operation', article: 'die', plural: 'Operationen', english: 'operation / surgery', example: 'Die Operation war erfolgreich.' },
      { german: 'allergisch', english: 'allergic', example: 'Ich bin allergisch gegen Katzen.' },
      { german: 'Allergie', article: 'die', plural: 'Allergien', english: 'allergy', example: 'Ich habe eine Pollenallergie.' },
      { german: 'Blutdruck', article: 'der', english: 'blood pressure', example: 'Mein Blutdruck ist zu hoch.' },
      { german: 'Versicherung', article: 'die', plural: 'Versicherungen', english: 'insurance', example: 'Die Krankenversicherung zahlt das.' },
      { german: 'sich erholen', english: 'to recover', example: 'Ich erhole mich langsam.' },
      { german: 'müde', english: 'tired', example: 'Ich bin sehr müde.' },
      { german: 'gesund', english: 'healthy', example: 'Bleib gesund!' },
      { german: 'krank', english: 'sick / ill', example: 'Er ist krank und bleibt zu Hause.' },
      { german: 'erholen', english: 'to recover / recuperate', example: 'Nach der Arbeit erholt er sich.' },
    ],
  },
  {
    id: 'a2-transport',
    name: 'Verkehr & Transport',
    nameEn: 'Traffic & Transport',
    icon: 'car',
    level: 'A2',
    words: [
      { german: 'Führerschein', article: 'der', plural: 'Führerscheine', english: 'driving licence', example: 'Ich habe meinen Führerschein mit 18 gemacht.' },
      { german: 'Stau', article: 'der', plural: 'Staus', english: 'traffic jam', example: 'Auf der Autobahn gibt es einen langen Stau.' },
      { german: 'Verspätung', article: 'die', plural: 'Verspätungen', english: 'delay', example: 'Der Zug hat 20 Minuten Verspätung.' },
      { german: 'Gleis', article: 'das', plural: 'Gleise', english: 'platform / track', example: 'Der Zug fährt von Gleis 7.' },
      { german: 'Fahrkarte', article: 'die', plural: 'Fahrkarten', english: 'ticket', example: 'Ich kaufe eine Fahrkarte am Automaten.' },
      { german: 'Umsteigen', english: 'to change (transport)', example: 'Sie müssen in Köln umsteigen.' },
      { german: 'Abfahrt', article: 'die', plural: 'Abfahrten', english: 'departure', example: 'Die Abfahrt ist um 14:30 Uhr.' },
      { german: 'Ankunft', article: 'die', plural: 'Ankünfte', english: 'arrival', example: 'Die Ankunft in Berlin ist um 18:00 Uhr.' },
      { german: 'Haltestelle', article: 'die', plural: 'Haltestellen', english: 'bus/tram stop', example: 'Die nächste Haltestelle ist 200 Meter entfernt.' },
      { german: 'tanken', english: 'to refuel', example: 'Ich muss tanken, der Tank ist leer.' },
      { german: 'parken', english: 'to park', example: 'Hier darf man nicht parken.' },
      { german: 'Parkplatz', article: 'der', plural: 'Parkplätze', english: 'parking space', example: 'Es gibt keinen Parkplatz in der Stadt.' },
      { german: 'Fahrplan', article: 'der', plural: 'Fahrpläne', english: 'timetable', example: 'Ich schaue im Fahrplan nach.' },
      { german: 'Rückfahrt', article: 'die', english: 'return journey', example: 'Die Rückfahrt dauert zwei Stunden.' },
      { german: 'Gepäck', article: 'das', english: 'luggage', example: 'Mein Gepäck ist zu schwer.' },
      { german: 'Reservierung', article: 'die', plural: 'Reservierungen', english: 'reservation', example: 'Ich habe eine Sitzplatzreservierung.' },
      { german: 'Landebahn', article: 'die', english: 'runway', example: 'Das Flugzeug landet auf der Landebahn.' },
      { german: 'kontrollieren', english: 'to check / inspect', example: 'Der Kontrolleur kontrolliert die Tickets.' },
      { german: 'überqueren', english: 'to cross', example: 'Wir überqueren die Brücke.' },
      { german: 'Umleitung', article: 'die', plural: 'Umleitungen', english: 'diversion / detour', example: 'Es gibt eine Umleitung wegen Bauarbeiten.' },
    ],
  },
  {
    id: 'a2-home',
    name: 'Wohnen & Haushalt',
    nameEn: 'Home & Household',
    icon: 'home',
    level: 'A2',
    words: [
      { german: 'Miete', article: 'die', plural: 'Mieten', english: 'rent', example: 'Die Miete ist sehr teuer in München.' },
      { german: 'Vermieter', article: 'der', plural: 'Vermieter', english: 'landlord', example: 'Der Vermieter wohnt im gleichen Haus.' },
      { german: 'Kaution', article: 'die', plural: 'Kautionen', english: 'security deposit', example: 'Die Kaution beträgt drei Monatsmieten.' },
      { german: 'Heizung', article: 'die', plural: 'Heizungen', english: 'heating', example: 'Die Heizung funktioniert nicht.' },
      { german: 'Strom', article: 'der', english: 'electricity', example: 'Die Stromrechnung ist sehr hoch.' },
      { german: 'Waschmaschine', article: 'die', plural: 'Waschmaschinen', english: 'washing machine', example: 'Die Waschmaschine ist kaputt.' },
      { german: 'Kühlschrank', article: 'der', plural: 'Kühlschränke', english: 'fridge', example: 'Der Kühlschrank ist leer.' },
      { german: 'Spülmaschine', article: 'die', plural: 'Spülmaschinen', english: 'dishwasher', example: 'Ich räume die Spülmaschine aus.' },
      { german: 'Möbel', article: 'die', english: 'furniture (pl.)', example: 'Die Möbel sind schön und modern.' },
      { german: 'Vorhang', article: 'der', plural: 'Vorhänge', english: 'curtain', example: 'Die Vorhänge im Wohnzimmer sind blau.' },
      { german: 'Regal', article: 'das', plural: 'Regale', english: 'shelf / shelves', example: 'Das Bücherregal ist voll.' },
      { german: 'Teppich', article: 'der', plural: 'Teppiche', english: 'carpet / rug', example: 'Der Teppich ist aus Wolle.' },
      { german: 'Treppe', article: 'die', plural: 'Treppen', english: 'stairs', example: 'Der Aufzug ist kaputt, wir nehmen die Treppe.' },
      { german: 'aufräumen', english: 'to tidy up', example: 'Ich muss mein Zimmer aufräumen.' },
      { german: 'putzen', english: 'to clean', example: 'Samstags putze ich die Wohnung.' },
      { german: 'Nachbar', article: 'der', plural: 'Nachbarn', english: 'neighbour (m.)', example: 'Mein Nachbar ist sehr laut.' },
      { german: 'Wohngemeinschaft', article: 'die', plural: 'Wohngemeinschaften', english: 'shared flat / house', example: 'Ich wohne in einer WG.' },
      { german: 'renovieren', english: 'to renovate', example: 'Wir renovieren die Küche.' },
      { german: 'einziehen', english: 'to move in', example: 'Wir ziehen nächsten Monat ein.' },
      { german: 'ausziehen', english: 'to move out', example: 'Sie zieht am Ende des Monats aus.' },
    ],
  },
  {
    id: 'a2-entertainment',
    name: 'Freizeit & Unterhaltung',
    nameEn: 'Leisure & Entertainment',
    icon: 'music',
    level: 'A2',
    words: [
      { german: 'Veranstaltung', article: 'die', plural: 'Veranstaltungen', english: 'event', example: 'Die Veranstaltung beginnt um 20 Uhr.' },
      { german: 'Konzert', article: 'das', plural: 'Konzerte', english: 'concert', example: 'Wir gehen morgen zu einem Konzert.' },
      { german: 'Ausstellung', article: 'die', plural: 'Ausstellungen', english: 'exhibition', example: 'Die Kunstausstellung ist sehr interessant.' },
      { german: 'Eintrittskarte', article: 'die', plural: 'Eintrittskarten', english: 'entry ticket', example: 'Die Eintrittskarten sind schon ausverkauft.' },
      { german: 'vorschlagen', english: 'to suggest', example: 'Ich schlage vor, ins Kino zu gehen.' },
      { german: 'sich verabreden', english: 'to make a date / meet up', example: 'Wir verabreden uns für Samstag.' },
      { german: 'Verabredung', article: 'die', plural: 'Verabredungen', english: 'date / appointment', example: 'Ich habe eine Verabredung um 19 Uhr.' },
      { german: 'Zeitvertreib', article: 'der', english: 'pastime', example: 'Lesen ist ein schöner Zeitvertreib.' },
      { german: 'Vereinsmitglied', article: 'das', english: 'club member', example: 'Ich bin Vereinsmitglied beim FC Bayern.' },
      { german: 'trainieren', english: 'to train / practise', example: 'Wir trainieren zweimal pro Woche.' },
      { german: 'Mannschaft', article: 'die', plural: 'Mannschaften', english: 'team', example: 'Unsere Mannschaft hat gewonnen.' },
      { german: 'Bewerbung', article: 'die', english: 'performance (arts)', example: 'Die Aufführung war wunderschön.' },
      { german: 'Regisseur', article: 'der', plural: 'Regisseure', english: 'director (film/theatre)', example: 'Der Regisseur ist sehr bekannt.' },
      { german: 'Roman', article: 'der', plural: 'Romane', english: 'novel', example: 'Ich lese gerade einen spannenden Roman.' },
      { german: 'Bühne', article: 'die', plural: 'Bühnen', english: 'stage', example: 'Die Schauspieler stehen auf der Bühne.' },
      { german: 'genießen', english: 'to enjoy', example: 'Ich genieße den Abend.' },
      { german: 'empfehlen', english: 'to recommend', example: 'Ich empfehle dieses Restaurant.' },
      { german: 'langweilig', english: 'boring', example: 'Der Film war sehr langweilig.' },
      { german: 'spannend', english: 'exciting / gripping', example: 'Das Buch ist sehr spannend.' },
      { german: 'entspannen', english: 'to relax', example: 'Am Wochenende entspanne ich mich.' },
    ],
  },
  {
    id: 'a2-environment',
    name: 'Umwelt & Natur',
    nameEn: 'Environment & Nature',
    icon: 'tree',
    level: 'A2',
    words: [
      { german: 'Umwelt', article: 'die', english: 'environment', example: 'Wir müssen die Umwelt schützen.' },
      { german: 'Klimawandel', article: 'der', english: 'climate change', example: 'Der Klimawandel ist ein großes Problem.' },
      { german: 'Müll', article: 'der', english: 'rubbish / trash', example: 'Bitte wirf den Müll nicht auf die Straße.' },
      { german: 'recyceln', english: 'to recycle', example: 'In Deutschland recyceln wir sehr viel.' },
      { german: 'Energie', article: 'die', english: 'energy', example: 'Wir brauchen mehr erneuerbare Energie.' },
      { german: 'Solaranlage', article: 'die', plural: 'Solaranlagen', english: 'solar panel system', example: 'Das Haus hat eine Solaranlage.' },
      { german: 'Abfall', article: 'der', plural: 'Abfälle', english: 'waste', example: 'Weniger Abfall produzieren ist wichtig.' },
      { german: 'Tier', article: 'das', plural: 'Tiere', english: 'animal', example: 'Wilde Tiere leben im Wald.' },
      { german: 'Pflanze', article: 'die', plural: 'Pflanzen', english: 'plant', example: 'Auf dem Balkon stehen viele Pflanzen.' },
      { german: 'Fluss', article: 'der', plural: 'Flüsse', english: 'river', example: 'Die Isar ist ein schöner Fluss in München.' },
      { german: 'Berg', article: 'der', plural: 'Berge', english: 'mountain', example: 'In Bayern gibt es viele Berge.' },
      { german: 'Meer', article: 'das', plural: 'Meere', english: 'sea / ocean', example: 'Im Sommer fahren wir ans Meer.' },
      { german: 'Wald', article: 'der', plural: 'Wälder', english: 'forest', example: 'Der Wald ist der Lunge der Erde.' },
      { german: 'sparen', english: 'to save (energy/money)', example: 'Wir sparen Energie, indem wir das Licht ausschalten.' },
      { german: 'schützen', english: 'to protect', example: 'Wir müssen die Natur schützen.' },
      { german: 'verschwenden', english: 'to waste', example: 'Verschwende kein Wasser!' },
      { german: 'nachhaltig', english: 'sustainable', example: 'Wir kaufen nachhaltige Produkte.' },
      { german: 'Treibhausgas', article: 'das', plural: 'Treibhausgase', english: 'greenhouse gas', example: 'CO2 ist ein Treibhausgas.' },
      { german: 'Bio-Produkt', article: 'das', plural: 'Bio-Produkte', english: 'organic product', example: 'Ich kaufe gerne Bio-Produkte.' },
      { german: 'Fahrgemeinschaft', article: 'die', english: 'carpool', example: 'Wir haben eine Fahrgemeinschaft zur Arbeit.' },
    ],
  },
  {
    id: 'a2-media',
    name: 'Medien & Kommunikation',
    nameEn: 'Media & Communication',
    icon: 'smartphone',
    level: 'A2',
    words: [
      { german: 'Nachricht', article: 'die', plural: 'Nachrichten', english: 'message / news', example: 'Ich schicke dir eine Nachricht.' },
      { german: 'Zeitschrift', article: 'die', plural: 'Zeitschriften', english: 'magazine', example: 'Ich lese eine Zeitschrift im Wartezimmer.' },
      { german: 'Sendung', article: 'die', plural: 'Sendungen', english: 'broadcast / programme', example: 'Die Sendung beginnt um 20:15 Uhr.' },
      { german: 'Werbung', article: 'die', plural: 'Werbungen', english: 'advertisement', example: 'Es gibt zu viel Werbung im Fernsehen.' },
      { german: 'hochladen', english: 'to upload', example: 'Ich lade das Foto hoch.' },
      { german: 'herunterladen', english: 'to download', example: 'Ich lade die App herunter.' },
      { german: 'Passwort', article: 'das', plural: 'Passwörter', english: 'password', example: 'Ich habe mein Passwort vergessen.' },
      { german: 'Kommentar', article: 'der', plural: 'Kommentare', english: 'comment', example: 'Sie schreibt einen Kommentar auf Instagram.' },
      { german: 'teilen', english: 'to share', example: 'Ich teile den Artikel auf Facebook.' },
      { german: 'Abonnement', article: 'das', plural: 'Abonnements', english: 'subscription', example: 'Ich habe ein Netflix-Abonnement.' },
      { german: 'suchen', english: 'to search', example: 'Ich suche die Information im Internet.' },
      { german: 'Drucker', article: 'der', plural: 'Drucker', english: 'printer', example: 'Der Drucker ist kaputt.' },
      { german: 'Bildschirm', article: 'der', plural: 'Bildschirme', english: 'screen', example: 'Der Bildschirm meines Laptops ist sehr hell.' },
      { german: 'Tastatur', article: 'die', plural: 'Tastaturen', english: 'keyboard', example: 'Ich tippe schnell auf der Tastatur.' },
      { german: 'klicken', english: 'to click', example: 'Klicke auf den Link.' },
      { german: 'speichern', english: 'to save (file)', example: 'Speichere die Datei bevor du gehst.' },
      { german: 'Datei', article: 'die', plural: 'Dateien', english: 'file', example: 'Schick mir die Datei per E-Mail.' },
      { german: 'Verbindung', article: 'die', plural: 'Verbindungen', english: 'connection', example: 'Die Internetverbindung ist langsam.' },
      { german: 'Netzwerk', article: 'das', plural: 'Netzwerke', english: 'network', example: 'Das WLAN-Netzwerk ist sicher.' },
      { german: 'Podcast', article: 'der', plural: 'Podcasts', english: 'podcast', example: 'Ich höre täglich Podcasts.' },
    ],
  },
  {
    id: 'a2-education',
    name: 'Bildung & Schule',
    nameEn: 'Education & School',
    icon: 'book',
    level: 'A2',
    words: [
      { german: 'Ausbildung', article: 'die', plural: 'Ausbildungen', english: 'vocational training', example: 'Er macht eine Ausbildung als Koch.' },
      { german: 'Studium', article: 'das', english: 'university studies', example: 'Das Studium dauert drei Jahre.' },
      { german: 'Abschluss', article: 'der', plural: 'Abschlüsse', english: 'degree / graduation', example: 'Sie macht nächstes Jahr ihren Abschluss.' },
      { german: 'Prüfung', article: 'die', plural: 'Prüfungen', english: 'exam', example: 'Die Prüfung war sehr schwer.' },
      { german: 'Note', article: 'die', plural: 'Noten', english: 'grade / mark', example: 'Ich habe eine gute Note bekommen.' },
      { german: 'bestehen', english: 'to pass (an exam)', example: 'Ich hoffe, ich bestehe die Prüfung.' },
      { german: 'durchfallen', english: 'to fail (an exam)', example: 'Er ist durch die Prüfung gefallen.' },
      { german: 'Hausaufgaben', article: 'die', english: 'homework', example: 'Ich mache meine Hausaufgaben.' },
      { german: 'Referat', article: 'das', plural: 'Referate', english: 'presentation / paper', example: 'Nächste Woche halte ich ein Referat.' },
      { german: 'Semester', article: 'das', plural: 'Semester', english: 'semester', example: 'Ich bin im dritten Semester.' },
      { german: 'Vorlesung', article: 'die', plural: 'Vorlesungen', english: 'lecture', example: 'Die Vorlesung beginnt um 9 Uhr.' },
      { german: 'Bibliothek', article: 'die', plural: 'Bibliotheken', english: 'library', example: 'Ich lerne oft in der Bibliothek.' },
      { german: 'Stipendium', article: 'das', plural: 'Stipendien', english: 'scholarship', example: 'Sie hat ein Stipendium bekommen.' },
      { german: 'Kurs', article: 'der', plural: 'Kurse', english: 'course', example: 'Ich mache einen Sprachkurs.' },
      { german: 'Zeugnis', article: 'das', plural: 'Zeugnisse', english: 'school report / certificate', example: 'Das Zeugnis war sehr gut.' },
      { german: 'unterrichten', english: 'to teach', example: 'Die Lehrerin unterrichtet Mathematik.' },
      { german: 'erklären', english: 'to explain', example: 'Kannst du mir das erklären?' },
      { german: 'verstehen', english: 'to understand', example: 'Ich verstehe das nicht.' },
      { german: 'wiederholen', english: 'to repeat / revise', example: 'Ich wiederhole den Stoff für die Prüfung.' },
      { german: 'Weiterbildung', article: 'die', english: 'further education / training', example: 'Ich mache eine Weiterbildung.' },
    ],
  },
];

export const grammarA2: GrammarRule[] = [
  {
    id: 'a2-perfekt',
    title: 'Das Perfekt — Vergangenheit',
    titleEn: 'The Perfect Tense — Past Actions',
    level: 'A2',
    explanation: 'Das Perfekt benutzen wir für abgeschlossene Handlungen in der Vergangenheit. Es wird mit "haben" oder "sein" + Partizip II gebildet.',
    explanationEn: 'We use the Perfekt for completed past actions. It is formed with "haben" or "sein" + past participle.',
    tables: [
      {
        headers: ['Infinitiv', 'Partizip II', 'Hilfsverb', 'Beispiel'],
        rows: [
          ['machen', 'gemacht', 'haben', 'Ich habe das gemacht.'],
          ['kaufen', 'gekauft', 'haben', 'Er hat Brot gekauft.'],
          ['fahren', 'gefahren', 'sein', 'Sie ist nach Berlin gefahren.'],
          ['gehen', 'gegangen', 'sein', 'Wir sind spazieren gegangen.'],
          ['kommen', 'gekommen', 'sein', 'Du bist früh gekommen.'],
          ['essen', 'gegessen', 'haben', 'Wir haben Pizza gegessen.'],
          ['schreiben', 'geschrieben', 'haben', 'Ich habe einen Brief geschrieben.'],
          ['sehen', 'gesehen', 'haben', 'Hast du den Film gesehen?'],
        ],
      },
    ],
    examples: [
      { german: 'Ich habe gestern viel gearbeitet.', english: 'I worked a lot yesterday.' },
      { german: 'Wir sind letzten Sommer nach Spanien gefahren.', english: 'We went to Spain last summer.' },
      { german: 'Er hat mir geholfen.', english: 'He helped me.' },
      { german: 'Sie ist heute Morgen früh aufgestanden.', english: 'She got up early this morning.' },
    ],
    tip: 'Verben der Bewegung (fahren, gehen, kommen, laufen) und des Zustandswechsels (werden, bleiben, aufwachen) nehmen "sein". Alle anderen nehmen "haben".',
  },
  {
    id: 'a2-dativ',
    title: 'Der Dativ — indirektes Objekt',
    titleEn: 'The Dative Case — Indirect Object',
    level: 'A2',
    explanation: 'Der Dativ bezeichnet das indirekte Objekt (wem?). Die Artikel ändern sich: der→dem, die→der, das→dem, ein→einem, eine→einer.',
    explanationEn: 'The dative marks the indirect object (to whom?). Articles change: der→dem, die→der, das→dem.',
    tables: [
      {
        headers: ['Kasus', 'maskulin', 'feminin', 'neutral', 'Plural'],
        rows: [
          ['Nominativ', 'der Mann', 'die Frau', 'das Kind', 'die Leute'],
          ['Akkusativ', 'den Mann', 'die Frau', 'das Kind', 'die Leute'],
          ['Dativ', 'dem Mann', 'der Frau', 'dem Kind', 'den Leuten'],
        ],
      },
      {
        headers: ['Dativpräpositionen', 'Bedeutung'],
        rows: [
          ['mit', 'with'],
          ['nach', 'after / to (cities)'],
          ['bei', 'at / near'],
          ['von', 'from / of'],
          ['zu', 'to (people/places)'],
          ['aus', 'from / out of'],
          ['seit', 'since / for'],
          ['gegenüber', 'opposite'],
        ],
      },
    ],
    examples: [
      { german: 'Ich gebe dem Mann den Schlüssel.', english: 'I give the man the key.' },
      { german: 'Sie hilft ihrer Mutter.', english: 'She helps her mother.' },
      { german: 'Ich fahre mit dem Bus.', english: 'I take the bus.' },
      { german: 'Seit einem Jahr lerne ich Deutsch.', english: 'I have been learning German for a year.' },
    ],
    tip: 'Im Dativ Plural bekommen alle Nomen die Endung "-n": die Männer → den Männern, die Kinder → den Kindern.',
  },
  {
    id: 'a2-konjunktionen',
    title: 'Konjunktionen — Nebensätze',
    titleEn: 'Conjunctions — Subordinate Clauses',
    level: 'A2',
    explanation: 'Konjunktionen wie "weil", "dass", "wenn" und "obwohl" leiten Nebensätze ein. Im Nebensatz steht das Verb am Ende.',
    explanationEn: 'Conjunctions like "weil", "dass", "wenn" and "obwohl" introduce subordinate clauses. The verb goes to the END of the clause.',
    tables: [
      {
        headers: ['Konjunktion', 'Bedeutung', 'Beispiel'],
        rows: [
          ['weil', 'because', 'Ich lerne Deutsch, weil ich in Deutschland arbeiten möchte.'],
          ['dass', 'that', 'Ich denke, dass das richtig ist.'],
          ['wenn', 'when / if', 'Wenn ich Zeit habe, gehe ich ins Kino.'],
          ['obwohl', 'although', 'Obwohl es regnet, gehe ich spazieren.'],
          ['damit', 'so that', 'Ich übe, damit ich besser werde.'],
          ['bevor', 'before', 'Bevor ich schlafe, lese ich ein Buch.'],
        ],
      },
    ],
    examples: [
      { german: 'Ich bin müde, weil ich schlecht geschlafen habe.', english: 'I am tired because I slept badly.' },
      { german: 'Er sagt, dass er kommen will.', english: 'He says that he wants to come.' },
      { german: 'Wenn das Wetter gut ist, fahren wir ans Meer.', english: 'If the weather is good, we go to the sea.' },
    ],
    tip: 'Merke: Verb ans Ende im Nebensatz! Bei trennbaren Verben bleibt das Präfix am Verb: "weil er aufsteht" (nicht: "weil er auf steht").',
  },
  {
    id: 'a2-komparativ',
    title: 'Komparativ und Superlativ',
    titleEn: 'Comparative and Superlative',
    level: 'A2',
    explanation: 'Komparativ: Adjektiv + -er (+ als). Superlativ: am + Adjektiv + -(e)sten oder der/die/das + Adjektiv + -(e)ste.',
    explanationEn: 'Comparative: adjective + -er (+ than). Superlative: am + adjective + -(e)sten.',
    tables: [
      {
        headers: ['Grundform', 'Komparativ', 'Superlativ'],
        rows: [
          ['schnell', 'schneller', 'am schnellsten'],
          ['groß', 'größer', 'am größten'],
          ['gut', 'besser', 'am besten'],
          ['viel', 'mehr', 'am meisten'],
          ['gern', 'lieber', 'am liebsten'],
          ['hoch', 'höher', 'am höchsten'],
          ['nah', 'näher', 'am nächsten'],
          ['alt', 'älter', 'am ältesten'],
        ],
      },
    ],
    examples: [
      { german: 'München ist größer als Nürnberg.', english: 'Munich is bigger than Nuremberg.' },
      { german: 'Das ist das beste Restaurant in der Stadt.', english: 'This is the best restaurant in the city.' },
      { german: 'Ich laufe schneller als mein Bruder.', english: 'I run faster than my brother.' },
      { german: 'Er fährt am liebsten Fahrrad.', english: 'He likes cycling the most.' },
    ],
    tip: 'Viele einsilbige Adjektive mit a, o, u bekommen Umlaut: alt→älter, groß→größer, jung→jünger, kurz→kürzer, lang→länger.',
  },
  {
    id: 'a2-reflexiv',
    title: 'Reflexive Verben',
    titleEn: 'Reflexive Verbs',
    level: 'A2',
    explanation: 'Reflexive Verben benutzen ein Reflexivpronomen (mich, dich, sich...). Sie beziehen sich auf das Subjekt zurück.',
    explanationEn: 'Reflexive verbs use a reflexive pronoun (myself, yourself, himself...). The action reflects back on the subject.',
    tables: [
      {
        headers: ['Pronomen', 'Reflexivpronomen (Akk.)', 'Beispiel'],
        rows: [
          ['ich', 'mich', 'Ich wasche mich.'],
          ['du', 'dich', 'Du freust dich.'],
          ['er/sie/es', 'sich', 'Er zieht sich an.'],
          ['wir', 'uns', 'Wir treffen uns.'],
          ['ihr', 'euch', 'Ihr beeilt euch.'],
          ['sie/Sie', 'sich', 'Sie erholen sich.'],
        ],
      },
    ],
    examples: [
      { german: 'Ich freue mich auf den Urlaub.', english: 'I am looking forward to the holiday.' },
      { german: 'Er zieht sich schnell an.', english: 'He gets dressed quickly.' },
      { german: 'Wir treffen uns um 19 Uhr.', english: 'We meet at 7 pm.' },
      { german: 'Sie hat sich erkältet.', english: 'She has caught a cold.' },
    ],
    tip: 'Häufige reflexive Verben: sich freuen, sich waschen, sich anziehen, sich treffen, sich erholen, sich beeilen, sich vorstellen, sich erinnern.',
  },
  {
    id: 'a2-praeteritum',
    title: 'Präteritum — sein, haben, Modalverben',
    titleEn: 'Simple Past — sein, haben, Modal Verbs',
    level: 'A2',
    explanation: 'Im Präteritum (schriftliche Vergangenheit) benutzen wir besonders: war (sein), hatte (haben) und die Modalverben.',
    explanationEn: 'In the Präteritum (written past tense) we especially use: war (sein), hatte (haben) and modal verbs.',
    tables: [
      {
        headers: ['Person', 'sein (war)', 'haben (hatte)', 'können (konnte)', 'müssen (musste)'],
        rows: [
          ['ich', 'war', 'hatte', 'konnte', 'musste'],
          ['du', 'warst', 'hattest', 'konntest', 'musstest'],
          ['er/sie/es', 'war', 'hatte', 'konnte', 'musste'],
          ['wir', 'waren', 'hatten', 'konnten', 'mussten'],
          ['ihr', 'wart', 'hattet', 'konntet', 'musstet'],
          ['sie/Sie', 'waren', 'hatten', 'konnten', 'mussten'],
        ],
      },
    ],
    examples: [
      { german: 'Als Kind war ich sehr sportlich.', english: 'As a child I was very sporty.' },
      { german: 'Wir hatten keine Zeit.', english: 'We had no time.' },
      { german: 'Er konnte nicht schlafen.', english: 'He could not sleep.' },
      { german: 'Sie musste früh aufstehen.', english: 'She had to get up early.' },
    ],
    tip: 'Im Gespräch: Perfekt. Im Schreiben: Präteritum. Aber war/hatte/konnte/musste sind auch im Gespräch normal.',
  },
];
