// B1 Level Study Data — Vocabulary & Grammar

import type { VocabTopic, GrammarRule } from './study-data';

export const vocabularyB1: VocabTopic[] = [
  {
    id: 'b1-society',
    name: 'Gesellschaft & Politik',
    nameEn: 'Society & Politics',
    icon: 'users',
    level: 'B1',
    words: [
      { german: 'Demokratie', article: 'die', english: 'democracy', example: 'Deutschland ist eine parlamentarische Demokratie.' },
      { german: 'Wahl', article: 'die', plural: 'Wahlen', english: 'election', example: 'Die Bundestagswahl findet alle vier Jahre statt.' },
      { german: 'Partei', article: 'die', plural: 'Parteien', english: 'political party', example: 'Es gibt viele Parteien im Bundestag.' },
      { german: 'Gesetz', article: 'das', plural: 'Gesetze', english: 'law', example: 'Das neue Gesetz tritt am 1. Januar in Kraft.' },
      { german: 'Recht', article: 'das', plural: 'Rechte', english: 'right / law', example: 'Jeder hat das Recht auf freie Meinung.' },
      { german: 'Steuern', article: 'die', english: 'taxes', example: 'In Deutschland zahlt man hohe Steuern.' },
      { german: 'Haushalt', article: 'der', plural: 'Haushalte', english: 'budget / household', example: 'Der staatliche Haushalt muss ausgeglichen sein.' },
      { german: 'Bürger', article: 'der', plural: 'Bürger', english: 'citizen', example: 'Alle Bürger haben gleiche Rechte.' },
      { german: 'Flüchtling', article: 'der', plural: 'Flüchtlinge', english: 'refugee', example: 'Viele Flüchtlinge kommen nach Europa.' },
      { german: 'Integration', article: 'die', english: 'integration', example: 'Integration braucht Zeit und Geduld.' },
      { german: 'Demonstration', article: 'die', plural: 'Demonstrationen', english: 'demonstration / protest', example: 'Tausende gingen zur Klimademonstration.' },
      { german: 'Protest', article: 'der', plural: 'Proteste', english: 'protest', example: 'Die Bevölkerung protestiert gegen das Gesetz.' },
      { german: 'Gleichberechtigung', article: 'die', english: 'equal rights', example: 'Gleichberechtigung ist ein wichtiges Thema.' },
      { german: 'Minderheit', article: 'die', plural: 'Minderheiten', english: 'minority', example: 'Minderheiten müssen geschützt werden.' },
      { german: 'Diskriminierung', article: 'die', english: 'discrimination', example: 'Diskriminierung ist verboten.' },
      { german: 'Solidarität', article: 'die', english: 'solidarity', example: 'Solidarität ist in Krisenzeiten wichtig.' },
      { german: 'Verantwortung', article: 'die', english: 'responsibility', example: 'Jeder trägt Verantwortung für die Gesellschaft.' },
      { german: 'Kompromiss', article: 'der', plural: 'Kompromisse', english: 'compromise', example: 'In der Politik braucht man Kompromisse.' },
      { german: 'Debatte', article: 'die', plural: 'Debatten', english: 'debate', example: 'Die Debatte über den Mindestlohn dauert an.' },
      { german: 'Volksabstimmung', article: 'die', english: 'referendum', example: 'Eine Volksabstimmung wurde abgehalten.' },
    ],
  },
  {
    id: 'b1-economics',
    name: 'Wirtschaft & Finanzen',
    nameEn: 'Economy & Finance',
    icon: 'trending-up',
    level: 'B1',
    words: [
      { german: 'Wirtschaft', article: 'die', english: 'economy', example: 'Die deutsche Wirtschaft ist stark.' },
      { german: 'Konjunktur', article: 'die', english: 'economic cycle', example: 'Die Konjunktur erholt sich langsam.' },
      { german: 'Inflation', article: 'die', english: 'inflation', example: 'Die Inflation steigt seit Monaten.' },
      { german: 'Krise', article: 'die', plural: 'Krisen', english: 'crisis', example: 'Die Wirtschaftskrise betrifft alle.' },
      { german: 'Investition', article: 'die', plural: 'Investitionen', english: 'investment', example: 'Investitionen in Bildung sind wichtig.' },
      { german: 'Schulden', article: 'die', english: 'debts', example: 'Er hat hohe Schulden bei der Bank.' },
      { german: 'Kredit', article: 'der', plural: 'Kredite', english: 'loan / credit', example: 'Die Bank hat ihm einen Kredit gegeben.' },
      { german: 'Aktie', article: 'die', plural: 'Aktien', english: 'share / stock', example: 'Er kauft Aktien als Geldanlage.' },
      { german: 'Unternehmen', article: 'das', plural: 'Unternehmen', english: 'company / enterprise', example: 'Das Unternehmen beschäftigt 500 Mitarbeiter.' },
      { german: 'Wettbewerb', article: 'der', english: 'competition', example: 'Der Wettbewerb auf dem Markt ist hart.' },
      { german: 'Markt', article: 'der', plural: 'Märkte', english: 'market', example: 'Der europäische Markt ist groß.' },
      { german: 'Exportieren', english: 'to export', example: 'Deutschland exportiert viele Autos.' },
      { german: 'Importieren', english: 'to import', example: 'Wir importieren Öl aus Norwegen.' },
      { german: 'Umsatz', article: 'der', plural: 'Umsätze', english: 'revenue / turnover', example: 'Der Umsatz ist dieses Jahr gestiegen.' },
      { german: 'Gewinn', article: 'der', plural: 'Gewinne', english: 'profit', example: 'Das Unternehmen macht großen Gewinn.' },
      { german: 'Verlust', article: 'der', plural: 'Verluste', english: 'loss', example: 'Die Firma hat Verluste gemacht.' },
      { german: 'Förderung', article: 'die', plural: 'Förderungen', english: 'funding / promotion', example: 'Die Regierung gibt Förderungen für Start-ups.' },
      { german: 'Insolvenz', article: 'die', english: 'insolvency / bankruptcy', example: 'Das Unternehmen hat Insolvenz angemeldet.' },
      { german: 'Haushalt', article: 'der', english: 'budget', example: 'Der Staatshaushalt muss ausgeglichen sein.' },
      { german: 'Zinssatz', article: 'der', plural: 'Zinssätze', english: 'interest rate', example: 'Der Zinssatz wurde gesenkt.' },
    ],
  },
  {
    id: 'b1-science',
    name: 'Wissenschaft & Technologie',
    nameEn: 'Science & Technology',
    icon: 'cpu',
    level: 'B1',
    words: [
      { german: 'Forschung', article: 'die', english: 'research', example: 'Die Forschung macht große Fortschritte.' },
      { german: 'Studie', article: 'die', plural: 'Studien', english: 'study / research paper', example: 'Eine neue Studie zeigt interessante Ergebnisse.' },
      { german: 'Experiment', article: 'das', plural: 'Experimente', english: 'experiment', example: 'Das Experiment war erfolgreich.' },
      { german: 'Ergebnis', article: 'das', plural: 'Ergebnisse', english: 'result', example: 'Die Ergebnisse wurden veröffentlicht.' },
      { german: 'Entdeckung', article: 'die', plural: 'Entdeckungen', english: 'discovery', example: 'Die Entdeckung des Penizillins war wichtig.' },
      { german: 'Entwicklung', article: 'die', plural: 'Entwicklungen', english: 'development', example: 'Die technische Entwicklung geht schnell.' },
      { german: 'künstliche Intelligenz', article: 'die', english: 'artificial intelligence (AI)', example: 'KI verändert viele Berufe.' },
      { german: 'Algorithmus', article: 'der', plural: 'Algorithmen', english: 'algorithm', example: 'Der Algorithmus analysiert die Daten.' },
      { german: 'Digitalisierung', article: 'die', english: 'digitalisation', example: 'Die Digitalisierung verändert unsere Welt.' },
      { german: 'Innovation', article: 'die', plural: 'Innovationen', english: 'innovation', example: 'Innovationen sind wichtig für den Fortschritt.' },
      { german: 'Patent', article: 'das', plural: 'Patente', english: 'patent', example: 'Sie hat ein Patent auf ihre Erfindung.' },
      { german: 'Labor', article: 'das', plural: 'Labore', english: 'laboratory', example: 'Die Forscher arbeiten im Labor.' },
      { german: 'Hypothesis', article: 'die', plural: 'Hypothesen', english: 'hypothesis', example: 'Die Hypothese wurde bestätigt.' },
      { german: 'Beweis', article: 'der', plural: 'Beweise', english: 'proof / evidence', example: 'Es gibt keine Beweise dafür.' },
      { german: 'Roboter', article: 'der', plural: 'Roboter', english: 'robot', example: 'Roboter werden in Fabriken eingesetzt.' },
      { german: 'Automation', article: 'die', english: 'automation', example: 'Automation ersetzt manche Berufe.' },
      { german: 'Daten', article: 'die', english: 'data', example: 'Die Daten werden verschlüsselt gespeichert.' },
      { german: 'Datenschutz', article: 'der', english: 'data protection', example: 'Datenschutz ist in Europa streng geregelt.' },
      { german: 'nachweisen', english: 'to prove / demonstrate', example: 'Die Studie weist nach, dass...' },
      { german: 'analysieren', english: 'to analyse', example: 'Wir analysieren die Daten.' },
    ],
  },
  {
    id: 'b1-culture',
    name: 'Kultur & Gesellschaft',
    nameEn: 'Culture & Society',
    icon: 'palette',
    level: 'B1',
    words: [
      { german: 'Tradition', article: 'die', plural: 'Traditionen', english: 'tradition', example: 'Das ist eine alte deutsche Tradition.' },
      { german: 'Brauchtum', article: 'das', english: 'customs and traditions', example: 'Das Brauchtum variiert von Region zu Region.' },
      { german: 'Vielfalt', article: 'die', english: 'diversity', example: 'Kulturelle Vielfalt bereichert die Gesellschaft.' },
      { german: 'Identität', article: 'die', plural: 'Identitäten', english: 'identity', example: 'Sprache ist Teil der kulturellen Identität.' },
      { german: 'Wert', article: 'der', plural: 'Werte', english: 'value', example: 'Freiheit und Gleichheit sind wichtige Werte.' },
      { german: 'Norm', article: 'die', plural: 'Normen', english: 'norm', example: 'Gesellschaftliche Normen verändern sich.' },
      { german: 'Vorurteil', article: 'das', plural: 'Vorurteile', english: 'prejudice', example: 'Vorurteile sind oft unbegründet.' },
      { german: 'Toleranz', article: 'die', english: 'tolerance', example: 'Toleranz ist in einer multikulturellen Gesellschaft wichtig.' },
      { german: 'Stereotype', article: 'das', plural: 'Stereotype', english: 'stereotype', example: 'Stereotype sind vereinfachende Vorstellungen.' },
      { german: 'Globalisierung', article: 'die', english: 'globalisation', example: 'Die Globalisierung vernetzt die Welt.' },
      { german: 'Erbe', article: 'das', english: 'heritage / inheritance', example: 'Das kulturelle Erbe muss erhalten werden.' },
      { german: 'Leitbild', article: 'das', plural: 'Leitbilder', english: 'role model / guiding image', example: 'Das Leitbild der Firma sind Nachhaltigkeit.' },
      { german: 'Gemeinschaft', article: 'die', plural: 'Gemeinschaften', english: 'community', example: 'Wir leben in einer Gemeinschaft.' },
      { german: 'Wohlstand', article: 'der', english: 'prosperity / wealth', example: 'Der Wohlstand in Deutschland ist hoch.' },
      { german: 'Gerechtigkeit', article: 'die', english: 'justice', example: 'Soziale Gerechtigkeit ist ein Ziel der Politik.' },
      { german: 'Freiheit', article: 'die', english: 'freedom', example: 'Meinungsfreiheit ist ein Grundrecht.' },
      { german: 'Pflicht', article: 'die', plural: 'Pflichten', english: 'duty / obligation', example: 'Steuern zahlen ist eine Pflicht.' },
      { german: 'Anerkennung', article: 'die', english: 'recognition / acknowledgement', example: 'Sie sucht Anerkennung für ihre Arbeit.' },
      { german: 'Wandel', article: 'der', english: 'change / transformation', example: 'Der gesellschaftliche Wandel ist schnell.' },
      { german: 'Einfluss', article: 'der', plural: 'Einflüsse', english: 'influence', example: 'Das Internet hat großen Einfluss auf die Kultur.' },
    ],
  },
  {
    id: 'b1-health-advanced',
    name: 'Gesundheit & Wohlbefinden',
    nameEn: 'Health & Wellbeing',
    icon: 'activity',
    level: 'B1',
    words: [
      { german: 'Wohlbefinden', article: 'das', english: 'wellbeing', example: 'Das Wohlbefinden ist wichtig für die Gesundheit.' },
      { german: 'Stress', article: 'der', english: 'stress', example: 'Chronischer Stress macht krank.' },
      { german: 'Burnout', article: 'der', english: 'burnout', example: 'Burnout ist eine ernste Erkrankung.' },
      { german: 'Prävention', article: 'die', english: 'prevention', example: 'Prävention ist besser als Behandlung.' },
      { german: 'Therapie', article: 'die', plural: 'Therapien', english: 'therapy', example: 'Er macht eine Therapie beim Psychologen.' },
      { german: 'Symptom', article: 'das', plural: 'Symptome', english: 'symptom', example: 'Die Symptome wurden stärker.' },
      { german: 'Diagnose', article: 'die', plural: 'Diagnosen', english: 'diagnosis', example: 'Die Diagnose war besorgniserregend.' },
      { german: 'Behandlung', article: 'die', plural: 'Behandlungen', english: 'treatment', example: 'Die Behandlung dauert sechs Wochen.' },
      { german: 'Rehabilitation', article: 'die', english: 'rehabilitation', example: 'Nach der Operation begann die Rehabilitation.' },
      { german: 'psychisch', english: 'psychological / mental', example: 'Psychische Gesundheit ist genauso wichtig.' },
      { german: 'körperlich', english: 'physical / bodily', example: 'Körperliche Aktivität fördert die Gesundheit.' },
      { german: 'Schlafmangel', article: 'der', english: 'sleep deprivation', example: 'Schlafmangel hat viele negative Folgen.' },
      { german: 'Ernährung', article: 'die', english: 'nutrition / diet', example: 'Eine ausgewogene Ernährung ist wichtig.' },
      { german: 'Sucht', article: 'die', plural: 'Süchte', english: 'addiction', example: 'Sucht ist eine Krankheit, keine Schwäche.' },
      { german: 'Einschränkung', article: 'die', plural: 'Einschränkungen', english: 'restriction / limitation', example: 'Die Einschränkungen wegen der Krankheit sind schwer.' },
      { german: 'Impfung', article: 'die', plural: 'Impfungen', english: 'vaccination', example: 'Impfungen schützen vor gefährlichen Krankheiten.' },
      { german: 'Epidemie', article: 'die', plural: 'Epidemien', english: 'epidemic', example: 'Die Epidemie breitete sich schnell aus.' },
      { german: 'Immunsystem', article: 'das', english: 'immune system', example: 'Sport stärkt das Immunsystem.' },
      { german: 'chronisch', english: 'chronic', example: 'Er leidet an einer chronischen Krankheit.' },
      { german: 'ausgewogen', english: 'balanced', example: 'Eine ausgewogene Ernährung ist empfehlenswert.' },
    ],
  },
  {
    id: 'b1-environment',
    name: 'Klimaschutz & Nachhaltigkeit',
    nameEn: 'Climate & Sustainability',
    icon: 'globe',
    level: 'B1',
    words: [
      { german: 'Klimaschutz', article: 'der', english: 'climate protection', example: 'Klimaschutz ist die größte Aufgabe unserer Zeit.' },
      { german: 'Treibhauseffekt', article: 'der', english: 'greenhouse effect', example: 'Der Treibhauseffekt erwärmt die Erde.' },
      { german: 'erneuerbar', english: 'renewable', example: 'Erneuerbare Energien sind die Zukunft.' },
      { german: 'Windenergie', article: 'die', english: 'wind energy', example: 'Windenergie ist eine saubere Energiequelle.' },
      { german: 'Artenschutz', article: 'der', english: 'species protection', example: 'Artenschutz verhindert das Aussterben von Tieren.' },
      { german: 'Emissionen', article: 'die', english: 'emissions', example: 'CO2-Emissionen müssen reduziert werden.' },
      { german: 'Kohlenstoffabdruck', article: 'der', english: 'carbon footprint', example: 'Ich versuche, meinen Kohlenstoffabdruck zu reduzieren.' },
      { german: 'Abholzung', article: 'die', english: 'deforestation', example: 'Die Abholzung des Regenwaldes ist ein Problem.' },
      { german: 'Ressourcen', article: 'die', english: 'resources', example: 'Natürliche Ressourcen sind begrenzt.' },
      { german: 'Kreislaufwirtschaft', article: 'die', english: 'circular economy', example: 'Die Kreislaufwirtschaft vermeidet Abfall.' },
      { german: 'Plastikfrei', english: 'plastic-free', example: 'Ich versuche, plastikfrei einzukaufen.' },
      { german: 'verbrauchen', english: 'to consume / use up', example: 'Wir verbrauchen zu viel Energie.' },
      { german: 'reduzieren', english: 'to reduce', example: 'Wir müssen unseren Konsum reduzieren.' },
      { german: 'kompensieren', english: 'to compensate / offset', example: 'Er kompensiert seine Flugreisen durch Baumpflanzungen.' },
      { german: 'Überschwemmung', article: 'die', plural: 'Überschwemmungen', english: 'flood', example: 'Überschwemmungen werden durch den Klimawandel häufiger.' },
      { german: 'Dürre', article: 'die', plural: 'Dürren', english: 'drought', example: 'Dürren zerstören die Ernte.' },
      { german: 'Biodiversität', article: 'die', english: 'biodiversity', example: 'Die Biodiversität ist weltweit bedroht.' },
      { german: 'fossilenBrennstoffe', article: 'die', english: 'fossil fuels', example: 'Fossile Brennstoffe müssen ersetzt werden.' },
      { german: 'Verantwortungsbewusstsein', article: 'das', english: 'sense of responsibility', example: 'Wir brauchen mehr Verantwortungsbewusstsein.' },
      { german: 'Generationengerechtigkeit', article: 'die', english: 'intergenerational equity', example: 'Generationengerechtigkeit bedeutet, für zukünftige Generationen zu sorgen.' },
    ],
  },
  {
    id: 'b1-work-advanced',
    name: 'Moderne Arbeitswelt',
    nameEn: 'Modern Work Life',
    icon: 'laptop',
    level: 'B1',
    words: [
      { german: 'Homeoffice', article: 'das', english: 'working from home', example: 'Seit der Pandemie arbeiten viele im Homeoffice.' },
      { german: 'Work-Life-Balance', article: 'die', english: 'work-life balance', example: 'Eine gute Work-Life-Balance ist wichtig.' },
      { german: 'Fachkräftemangel', article: 'der', english: 'skilled labour shortage', example: 'Der Fachkräftemangel ist ein Problem in Deutschland.' },
      { german: 'Digitalisierung', article: 'die', english: 'digitalisation', example: 'Die Digitalisierung verändert die Arbeitswelt.' },
      { german: 'Automatisierung', article: 'die', english: 'automation', example: 'Automatisierung ersetzt einfache Jobs.' },
      { german: 'Weiterbildung', article: 'die', english: 'further training', example: 'Lebenslanges Lernen und Weiterbildung sind wichtig.' },
      { german: 'Start-up', article: 'das', plural: 'Start-ups', english: 'start-up', example: 'Das Berliner Start-up wurde für 50 Millionen Euro verkauft.' },
      { german: 'Freelancer', article: 'der', plural: 'Freelancer', english: 'freelancer', example: 'Sie arbeitet als Freelancerin im Marketing.' },
      { german: 'Netzwerk', article: 'das', plural: 'Netzwerke', english: 'network', example: 'Ein gutes Netzwerk hilft bei der Karriere.' },
      { german: 'Karriere', article: 'die', plural: 'Karrieren', english: 'career', example: 'Sie hat eine beeindruckende Karriere gemacht.' },
      { german: 'Kündigung', article: 'die', plural: 'Kündigungen', english: 'dismissal / notice', example: 'Er hat die Kündigung per Brief erhalten.' },
      { german: 'Bewerbungsunterlagen', article: 'die', english: 'application documents', example: 'Bitte schicken Sie uns Ihre Bewerbungsunterlagen.' },
      { german: 'Einstellungsgespräch', article: 'das', english: 'job interview', example: 'Das Einstellungsgespräch war sehr intensiv.' },
      { german: 'Probezeit', article: 'die', english: 'probation period', example: 'Die Probezeit beträgt sechs Monate.' },
      { german: 'Elternzeit', article: 'die', english: 'parental leave', example: 'Er ist sechs Monate in Elternzeit.' },
      { german: 'mobil arbeiten', english: 'to work remotely / mobile', example: 'Ich kann von überall mobil arbeiten.' },
      { german: 'Teamarbeit', article: 'die', english: 'teamwork', example: 'Teamarbeit ist in modernen Unternehmen wichtig.' },
      { german: 'Führungsqualität', article: 'die', plural: 'Führungsqualitäten', english: 'leadership quality', example: 'Gute Führungsqualitäten sind gefragt.' },
      { german: 'Projekmanagement', article: 'das', english: 'project management', example: 'Sie ist zertifiziert in Projektmanagement.' },
      { german: 'Burn-out-Prävention', article: 'die', english: 'burnout prevention', example: 'Unternehmen investieren in Burnout-Prävention.' },
    ],
  },
];

export const grammarB1: GrammarRule[] = [
  {
    id: 'b1-konjunktiv2',
    title: 'Konjunktiv II — Wünsche und Hypothesen',
    titleEn: 'Subjunctive II — Wishes and Hypotheticals',
    level: 'B1',
    explanation: 'Der Konjunktiv II drückt Wünsche, Hypothesen und höfliche Bitten aus. Häufigste Formen: würde + Infinitiv, wäre, hätte, könnte, sollte, müsste.',
    explanationEn: 'Subjunctive II expresses wishes, hypotheticals, and polite requests. Most common: würde + infinitive, wäre, hätte, könnte, sollte, müsste.',
    tables: [
      {
        headers: ['Person', 'würde', 'wäre (sein)', 'hätte (haben)', 'könnte (können)'],
        rows: [
          ['ich', 'würde', 'wäre', 'hätte', 'könnte'],
          ['du', 'würdest', 'wärst', 'hättest', 'könntest'],
          ['er/sie/es', 'würde', 'wäre', 'hätte', 'könnte'],
          ['wir', 'würden', 'wären', 'hätten', 'könnten'],
          ['ihr', 'würdet', 'wärt', 'hättet', 'könntet'],
          ['sie/Sie', 'würden', 'wären', 'hätten', 'könnten'],
        ],
      },
    ],
    examples: [
      { german: 'Ich würde gerne nach Japan reisen.', english: 'I would love to travel to Japan.' },
      { german: 'Wenn ich reich wäre, würde ich die Welt bereisen.', english: 'If I were rich, I would travel the world.' },
      { german: 'Könntest du mir bitte helfen?', english: 'Could you please help me?' },
      { german: 'Ich hätte gerne einen Kaffee.', english: 'I would like a coffee, please.' },
    ],
    tip: 'Für die meisten Verben: würde + Infinitiv. Ausnahmen direkt konjugieren: wäre (sein), hätte (haben), könnte (können), müsste (müssen), sollte (sollen), dürfte (dürfen).',
  },
  {
    id: 'b1-passiv',
    title: 'Das Passiv — Vorgangspassiv',
    titleEn: 'The Passive Voice',
    level: 'B1',
    explanation: 'Das Passiv betont die Handlung, nicht den Handelnden. Bildung: werden + Partizip II. Für den Handelnden: "von + Dativ".',
    explanationEn: 'The passive emphasises the action, not the person doing it. Formation: werden + past participle. For the agent: "von + dative".',
    tables: [
      {
        headers: ['Zeitform', 'Bildung', 'Beispiel'],
        rows: [
          ['Präsens', 'wird + Partizip II', 'Das Haus wird gebaut.'],
          ['Präteritum', 'wurde + Partizip II', 'Das Haus wurde gebaut.'],
          ['Perfekt', 'ist + Partizip II + worden', 'Das Haus ist gebaut worden.'],
          ['Futur', 'wird + Partizip II + werden', 'Das Haus wird gebaut werden.'],
        ],
      },
    ],
    examples: [
      { german: 'Das Buch wurde von Goethe geschrieben.', english: 'The book was written by Goethe.' },
      { german: 'Die Tür wird um 20 Uhr geschlossen.', english: 'The door is closed at 8 pm.' },
      { german: 'Das Gesetz wurde gestern verabschiedet.', english: 'The law was passed yesterday.' },
      { german: 'Der Brief ist bereits verschickt worden.', english: 'The letter has already been sent.' },
    ],
    tip: 'Aktiv: "Die Polizei verhaftet den Täter." Passiv: "Der Täter wird (von der Polizei) verhaftet." Im Passiv ist der Handelnde optional.',
  },
  {
    id: 'b1-relativsatz',
    title: 'Relativsätze',
    titleEn: 'Relative Clauses',
    level: 'B1',
    explanation: 'Relativsätze beschreiben ein Nomen genauer. Das Relativpronomen richtet sich nach Genus und Kasus des Bezugsnomens.',
    explanationEn: 'Relative clauses describe a noun more precisely. The relative pronoun agrees in gender and case with the noun it refers to.',
    tables: [
      {
        headers: ['Kasus', 'maskulin', 'feminin', 'neutral', 'Plural'],
        rows: [
          ['Nominativ', 'der', 'die', 'das', 'die'],
          ['Akkusativ', 'den', 'die', 'das', 'die'],
          ['Dativ', 'dem', 'der', 'dem', 'denen'],
          ['Genitiv', 'dessen', 'deren', 'dessen', 'deren'],
        ],
      },
    ],
    examples: [
      { german: 'Das ist der Mann, der mir geholfen hat.', english: 'This is the man who helped me.' },
      { german: 'Das Buch, das ich lese, ist sehr spannend.', english: 'The book I am reading is very exciting.' },
      { german: 'Ich suche eine Wohnung, die in der Stadtmitte liegt.', english: 'I am looking for a flat located in the city centre.' },
      { german: 'Das ist die Frau, deren Auto gestohlen wurde.', english: 'This is the woman whose car was stolen.' },
    ],
    tip: 'Das Relativpronomen kommt direkt nach dem Bezugsnomen (oder nach einem Komma). Das Verb im Relativsatz steht ans Ende.',
  },
  {
    id: 'b1-zweistellige-prap',
    title: 'Wechselpräpositionen (2-Wege-Präpositionen)',
    titleEn: 'Two-way Prepositions',
    level: 'B1',
    explanation: 'Diese Präpositionen stehen mit Akkusativ (Bewegung, wohin?) oder Dativ (Lage, wo?): in, an, auf, über, unter, neben, hinter, vor, zwischen.',
    explanationEn: 'These prepositions take accusative (movement, where to?) or dative (location, where?): in, an, auf, über, unter, neben, hinter, vor, zwischen.',
    tables: [
      {
        headers: ['Frage', 'Kasus', 'Beispiel'],
        rows: [
          ['Wo? (Lage)', 'Dativ', 'Das Buch liegt auf dem Tisch.'],
          ['Wohin? (Bewegung)', 'Akkusativ', 'Ich lege das Buch auf den Tisch.'],
          ['Wo?', 'Dativ', 'Er sitzt in dem / im Cafe.'],
          ['Wohin?', 'Akkusativ', 'Er geht in das / ins Cafe.'],
        ],
      },
    ],
    examples: [
      { german: 'Das Bild hängt an der Wand. (Dativ)', english: 'The picture hangs on the wall.' },
      { german: 'Ich hänge das Bild an die Wand. (Akkusativ)', english: 'I hang the picture on the wall.' },
      { german: 'Die Katze liegt unter dem Tisch.', english: 'The cat is lying under the table.' },
      { german: 'Die Katze läuft unter den Tisch.', english: 'The cat runs under the table.' },
    ],
    tip: 'Trick: "Wo?" = Dativ (statisch). "Wohin?" = Akkusativ (Bewegung). Kontrakte: in dem = im, an dem = am, in das = ins, an das = ans.',
  },
  {
    id: 'b1-genitiv',
    title: 'Der Genitiv — Zugehörigkeit',
    titleEn: 'The Genitive Case — Possession',
    level: 'B1',
    explanation: 'Der Genitiv zeigt Zugehörigkeit (wessen?). Maskulin/neutral: des + -(e)s. Feminin: der. Plural: der.',
    explanationEn: 'The genitive shows possession (whose?). Masculine/neuter: des + -(e)s. Feminine: der. Plural: der.',
    tables: [
      {
        headers: ['Genus', 'bestimmter Artikel', 'Beispiel'],
        rows: [
          ['maskulin', 'des + -(e)s am Nomen', 'das Auto des Mannes'],
          ['feminin', 'der', 'die Tasche der Frau'],
          ['neutral', 'des + -(e)s am Nomen', 'der Name des Kindes'],
          ['Plural', 'der', 'die Häuser der Leute'],
        ],
      },
    ],
    examples: [
      { german: 'Das ist das Auto meines Vaters.', english: 'This is my father\'s car.' },
      { german: 'Am Ende des Films gibt es eine Überraschung.', english: 'At the end of the film there is a surprise.' },
      { german: 'Die Hauptstadt Deutschlands ist Berlin.', english: 'The capital of Germany is Berlin.' },
      { german: 'Wegen des Regens blieben wir zu Hause.', english: 'Because of the rain we stayed at home.' },
    ],
    tip: 'Genitivpräpositionen: wegen (because of), während (during), trotz (despite), statt (instead of), aufgrund (due to), innerhalb (within).',
  },
  {
    id: 'b1-indirekte-rede',
    title: 'Indirekte Rede',
    titleEn: 'Reported Speech',
    level: 'B1',
    explanation: 'Indirekte Rede gibt wieder, was jemand gesagt hat. Wir benutzen: sagen/berichten/erklären + dass oder Konjunktiv I/II.',
    explanationEn: 'Reported speech conveys what someone said. We use: sagen + dass, or Konjunktiv I/II.',
    tables: [
      {
        headers: ['Direkte Rede', 'Indirekte Rede (mit dass)', 'Konjunktiv I'],
        rows: [
          ['"Ich bin müde."', 'Er sagt, dass er müde ist.', 'Er sei müde.'],
          ['"Ich habe Hunger."', 'Sie sagt, dass sie Hunger hat.', 'Sie habe Hunger.'],
          ['"Wir kommen morgen."', 'Sie sagen, dass sie morgen kommen.', 'Sie kämen morgen.'],
        ],
      },
    ],
    examples: [
      { german: 'Der Arzt sagt, dass ich mehr schlafen soll.', english: 'The doctor says that I should sleep more.' },
      { german: 'Sie berichtet, dass der Zug Verspätung hat.', english: 'She reports that the train is delayed.' },
      { german: 'Er erklärt, dass er kein Fleisch isst.', english: 'He explains that he does not eat meat.' },
      { german: 'Die Nachrichten melden, die Preise steigen weiter.', english: 'The news reports that prices continue to rise.' },
    ],
    tip: 'Im Alltag benutzen die meisten Deutschen "sagen, dass" + Indikativ. Konjunktiv I ist formeller und wird in Zeitungen und Nachrichten verwendet.',
  },
];
